import { normalizeLocaleCode } from '@/i18n/localeRegistry';

const en = {
  careEyebrow: 'PRIVATE CARE TIMELINE', careTitle: 'Visits, scans and follow-ups in one place.', addCareEntry: 'Add care entry', editCareEntry: 'Edit care entry', type: 'Type', date: 'Date', time: 'Time', doctorProvider: 'Doctor / provider', facility: 'Hospital / clinic / lab', purpose: 'Purpose', questionsToAsk: 'Questions to ask', onePerLine: 'One per line', status: 'Status', notesAfterVisit: 'Notes after visit', testsPrescribed: 'Tests / scans prescribed', cancel: 'Cancel', save: 'Save', timeline: 'Timeline', noEntries: 'No entries yet.', scheduled: 'Scheduled', completed: 'Completed', cancelled: 'Cancelled',
  foodEyebrow: 'JANANI FOOD GUIDE', foodTitle: 'Simple nourishment for pregnancy', balancedTitle: 'Build every plate gently', hydrationTitle: 'Hydration matters', foodSafetyTitle: 'Food safety first', carePlusMealTitle: 'Care+ meal support', openCarePlus: 'Open Care+',
} as const;

export type CareFoodKey = keyof typeof en;
type CareFoodPack = Partial<Record<CareFoodKey, string>>;

const packs: Record<string, CareFoodPack> = {
  en,
  te: {
    careEyebrow: 'వ్యక్తిగత సంరక్షణ టైమ్‌లైన్', careTitle: 'విజిట్లు, స్కాన్లు మరియు ఫాలో-అప్స్ ఒకేచోట.', addCareEntry: 'సంరక్షణ నమోదు జోడించండి', editCareEntry: 'సంరక్షణ నమోదు మార్చండి', type: 'రకం', date: 'తేదీ', time: 'సమయం', doctorProvider: 'డాక్టర్ / సేవాదారు', facility: 'హాస్పిటల్ / క్లినిక్ / ల్యాబ్', purpose: 'ఉద్దేశ్యం', questionsToAsk: 'అడగాల్సిన ప్రశ్నలు', onePerLine: 'ప్రతి లైనులో ఒకటి', status: 'స్థితి', notesAfterVisit: 'విజిట్ తర్వాత గమనికలు', testsPrescribed: 'సూచించిన పరీక్షలు / స్కాన్లు', cancel: 'రద్దు', save: 'సేవ్', timeline: 'టైమ్‌లైన్', noEntries: 'ఇంకా నమోదులు లేవు.', scheduled: 'షెడ్యూల్ చేయబడింది', completed: 'పూర్తైంది', cancelled: 'రద్దైంది',
    foodEyebrow: 'జనని ఆహార మార్గదర్శి', foodTitle: 'గర్భధారణకు సరళమైన పోషణ', balancedTitle: 'ప్రతి పళ్లెంను సమతుల్యంగా నిర్మించండి', hydrationTitle: 'తగినంత నీరు ముఖ్యం', foodSafetyTitle: 'ఆహార భద్రత ముందుగా', carePlusMealTitle: 'కేర్+ భోజన సహాయం', openCarePlus: 'కేర్+ తెరవండి',
  },
  hi: {
    careEyebrow: 'निजी केयर टाइमलाइन', careTitle: 'विज़िट, स्कैन और फॉलो-अप एक ही जगह।', addCareEntry: 'केयर एंट्री जोड़ें', editCareEntry: 'केयर एंट्री संपादित करें', type: 'प्रकार', date: 'तारीख', time: 'समय', doctorProvider: 'डॉक्टर / प्रदाता', facility: 'अस्पताल / क्लिनिक / लैब', purpose: 'उद्देश्य', questionsToAsk: 'पूछने के प्रश्न', onePerLine: 'हर पंक्ति में एक', status: 'स्थिति', notesAfterVisit: 'विज़िट के बाद नोट्स', testsPrescribed: 'बताए गए टेस्ट / स्कैन', cancel: 'रद्द करें', save: 'सेव करें', timeline: 'टाइमलाइन', noEntries: 'अभी कोई एंट्री नहीं है।', scheduled: 'निर्धारित', completed: 'पूरा हुआ', cancelled: 'रद्द हुआ',
    foodEyebrow: 'जननी फ़ूड गाइड', foodTitle: 'गर्भावस्था के लिए सरल पोषण', balancedTitle: 'हर प्लेट को संतुलित रखें', hydrationTitle: 'पर्याप्त पानी ज़रूरी है', foodSafetyTitle: 'खाद्य सुरक्षा पहले', carePlusMealTitle: 'केयर+ भोजन सहायता', openCarePlus: 'केयर+ खोलें',
  },
  ta: { careEyebrow:'தனிப்பட்ட பராமரிப்பு காலவரிசை', careTitle:'வருகைகள், ஸ்கான்கள் மற்றும் பின்தொடர்வுகள் ஒரே இடத்தில்.', addCareEntry:'பராமரிப்பு பதிவைச் சேர்க்கவும்', editCareEntry:'பராமரிப்பு பதிவைத் திருத்தவும்', type:'வகை', date:'தேதி', time:'நேரம்', doctorProvider:'மருத்துவர் / வழங்குநர்', facility:'மருத்துவமனை / கிளினிக் / ஆய்வகம்', purpose:'நோக்கம்', questionsToAsk:'கேட்க வேண்டிய கேள்விகள்', onePerLine:'ஒரு வரிக்கு ஒன்று', status:'நிலை', notesAfterVisit:'வருகைக்குப் பிந்தைய குறிப்புகள்', testsPrescribed:'பரிந்துரைக்கப்பட்ட பரிசோதனைகள் / ஸ்கான்கள்', cancel:'ரத்து செய்', save:'சேமி', timeline:'காலவரிசை', noEntries:'இன்னும் பதிவுகள் இல்லை.', scheduled:'திட்டமிடப்பட்டது', completed:'முடிந்தது', cancelled:'ரத்து செய்யப்பட்டது', foodEyebrow:'ஜனனி உணவு வழிகாட்டி', foodTitle:'கர்ப்பகாலத்திற்கு எளிய ஊட்டச்சத்து', balancedTitle:'ஒவ்வொரு தட்டையும் சமநிலையாக அமைக்கவும்', hydrationTitle:'நீர்ப்பாசனம் முக்கியம்', foodSafetyTitle:'உணவு பாதுகாப்பு முதலில்', carePlusMealTitle:'கேர்+ உணவு ஆதரவு', openCarePlus:'கேர்+ திறக்கவும்' },
  kn: { careEyebrow:'ಖಾಸಗಿ ಕೇರ್ ಟೈಮ್‌ಲೈನ್', careTitle:'ಭೇಟಿಗಳು, ಸ್ಕ್ಯಾನ್‌ಗಳು ಮತ್ತು ಫಾಲೋ-ಅಪ್‌ಗಳು ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ.', addCareEntry:'ಕೇರ್ ದಾಖಲೆ ಸೇರಿಸಿ', editCareEntry:'ಕೇರ್ ದಾಖಲೆ ಸಂಪಾದಿಸಿ', type:'ಪ್ರಕಾರ', date:'ದಿನಾಂಕ', time:'ಸಮಯ', doctorProvider:'ವೈದ್ಯರು / ಪೂರೈಕೆದಾರ', facility:'ಆಸ್ಪತ್ರೆ / ಕ್ಲಿನಿಕ್ / ಲ್ಯಾಬ್', purpose:'ಉದ್ದೇಶ', questionsToAsk:'ಕೇಳಬೇಕಾದ ಪ್ರಶ್ನೆಗಳು', onePerLine:'ಪ್ರತಿ ಸಾಲಿಗೆ ಒಂದು', status:'ಸ್ಥಿತಿ', notesAfterVisit:'ಭೇಟಿಯ ನಂತರದ ಟಿಪ್ಪಣಿಗಳು', testsPrescribed:'ಸೂಚಿಸಿದ ಪರೀಕ್ಷೆಗಳು / ಸ್ಕ್ಯಾನ್‌ಗಳು', cancel:'ರದ್ದು', save:'ಉಳಿಸಿ', timeline:'ಟೈಮ್‌ಲೈನ್', noEntries:'ಇನ್ನೂ ದಾಖಲೆಗಳಿಲ್ಲ.', scheduled:'ನಿಗದಿಯಾಗಿದೆ', completed:'ಪೂರ್ಣಗೊಂಡಿದೆ', cancelled:'ರದ್ದಾಗಿದೆ', foodEyebrow:'ಜನನಿ ಆಹಾರ ಮಾರ್ಗದರ್ಶಿ', foodTitle:'ಗರ್ಭಧಾರಣೆಗೆ ಸರಳ ಪೋಷಣೆ', balancedTitle:'ಪ್ರತಿ ತಟ್ಟೆಯನ್ನು ಸಮತೋಲನಗೊಳಿಸಿ', hydrationTitle:'ನೀರು ಮುಖ್ಯ', foodSafetyTitle:'ಆಹಾರ ಸುರಕ್ಷತೆ ಮೊದಲು', carePlusMealTitle:'ಕೇರ್+ ಊಟ ಸಹಾಯ', openCarePlus:'ಕೇರ್+ ತೆರೆಯಿರಿ' },
  ml: { careEyebrow:'സ്വകാര്യ പരിചരണ സമയരേഖ', careTitle:'സന്ദർശനങ്ങൾ, സ്കാനുകൾ, ഫോളോ-അപ്പുകൾ ഒരിടത്ത്.', addCareEntry:'പരിചരണ എൻട്രി ചേർക്കുക', editCareEntry:'പരിചരണ എൻട്രി തിരുത്തുക', type:'തരം', date:'തീയതി', time:'സമയം', doctorProvider:'ഡോക്ടർ / സേവനദാതാവ്', facility:'ആശുപത്രി / ക്ലിനിക് / ലാബ്', purpose:'ഉദ്ദേശ്യം', questionsToAsk:'ചോദിക്കാനുള്ള ചോദ്യങ്ങൾ', onePerLine:'ഓരോ വരിയിലും ഒന്ന്', status:'നില', notesAfterVisit:'സന്ദർശനത്തിന് ശേഷമുള്ള കുറിപ്പുകൾ', testsPrescribed:'നിർദേശിച്ച പരിശോധനകൾ / സ്കാനുകൾ', cancel:'റദ്ദാക്കുക', save:'സേവ് ചെയ്യുക', timeline:'സമയരേഖ', noEntries:'ഇനിയും എൻട്രികളില്ല.', scheduled:'ഷെഡ്യൂൾ ചെയ്തു', completed:'പൂർത്തിയായി', cancelled:'റദ്ദാക്കി', foodEyebrow:'ജനനി ഭക്ഷണ മാർഗ്ഗനിർദ്ദേശം', foodTitle:'ഗർഭകാലത്തിനുള്ള ലളിതമായ പോഷണം', balancedTitle:'ഓരോ പ്ലേറ്റും സമതുലിതമാക്കുക', hydrationTitle:'ജലാംശം പ്രധാനമാണ്', foodSafetyTitle:'ഭക്ഷ്യ സുരക്ഷ ആദ്യം', carePlusMealTitle:'കെയർ+ ഭക്ഷണ സഹായം', openCarePlus:'കെയർ+ തുറക്കുക' },
  mr: { careEyebrow:'खाजगी केअर टाइमलाइन', careTitle:'भेटी, स्कॅन आणि फॉलो-अप एकाच ठिकाणी.', addCareEntry:'केअर नोंद जोडा', editCareEntry:'केअर नोंद संपादित करा', type:'प्रकार', date:'तारीख', time:'वेळ', doctorProvider:'डॉक्टर / प्रदाता', facility:'रुग्णालय / क्लिनिक / लॅब', purpose:'उद्देश', questionsToAsk:'विचारायचे प्रश्न', onePerLine:'प्रत्येक ओळीत एक', status:'स्थिती', notesAfterVisit:'भेटीनंतरच्या नोंदी', testsPrescribed:'सुचवलेल्या चाचण्या / स्कॅन', cancel:'रद्द करा', save:'जतन करा', timeline:'टाइमलाइन', noEntries:'अजून नोंदी नाहीत.', scheduled:'नियोजित', completed:'पूर्ण', cancelled:'रद्द', foodEyebrow:'जननी आहार मार्गदर्शक', foodTitle:'गर्भावस्थेसाठी साधे पोषण', balancedTitle:'प्रत्येक ताट संतुलित ठेवा', hydrationTitle:'पाणी महत्त्वाचे आहे', foodSafetyTitle:'अन्न सुरक्षितता प्रथम', carePlusMealTitle:'केअर+ भोजन सहाय्य', openCarePlus:'केअर+ उघडा' },
  bn: { careEyebrow:'ব্যক্তিগত কেয়ার টাইমলাইন', careTitle:'ভিজিট, স্ক্যান ও ফলো-আপ এক জায়গায়।', addCareEntry:'কেয়ার এন্ট্রি যোগ করুন', editCareEntry:'কেয়ার এন্ট্রি সম্পাদনা করুন', type:'ধরন', date:'তারিখ', time:'সময়', doctorProvider:'ডাক্তার / প্রদানকারী', facility:'হাসপাতাল / ক্লিনিক / ল্যাব', purpose:'উদ্দেশ্য', questionsToAsk:'জিজ্ঞাসার প্রশ্ন', onePerLine:'প্রতি লাইনে একটি', status:'অবস্থা', notesAfterVisit:'ভিজিটের পর নোট', testsPrescribed:'নির্দেশিত পরীক্ষা / স্ক্যান', cancel:'বাতিল', save:'সংরক্ষণ', timeline:'টাইমলাইন', noEntries:'এখনও কোনো এন্ট্রি নেই।', scheduled:'নির্ধারিত', completed:'সম্পন্ন', cancelled:'বাতিল', foodEyebrow:'জননী খাদ্য নির্দেশিকা', foodTitle:'গর্ভাবস্থার জন্য সহজ পুষ্টি', balancedTitle:'প্রতিটি প্লেট ভারসাম্যপূর্ণ করুন', hydrationTitle:'পানি গুরুত্বপূর্ণ', foodSafetyTitle:'খাদ্য নিরাপত্তা আগে', carePlusMealTitle:'কেয়ার+ খাবার সহায়তা', openCarePlus:'কেয়ার+ খুলুন' },
  gu: { careEyebrow:'ખાનગી કાળજી સમયરેખા', careTitle:'મુલાકાતો, સ્કેન અને ફોલોઅપ એક જગ્યાએ.', addCareEntry:'કાળજી એન્ટ્રી ઉમેરો', editCareEntry:'કાળજી એન્ટ્રી સંપાદિત કરો', type:'પ્રકાર', date:'તારીખ', time:'સમય', doctorProvider:'ડૉક્ટર / પ્રદાતા', facility:'હોસ્પિટલ / ક્લિનિક / લેબ', purpose:'હેતુ', questionsToAsk:'પૂછવાના પ્રશ્નો', onePerLine:'દર લાઇનમાં એક', status:'સ્થિતિ', notesAfterVisit:'મુલાકાત પછીની નોંધો', testsPrescribed:'સૂચવેલ ટેસ્ટ / સ્કેન', cancel:'રદ કરો', save:'સાચવો', timeline:'સમયરેખા', noEntries:'હજી એન્ટ્રીઓ નથી.', scheduled:'નિર્ધારિત', completed:'પૂર્ણ', cancelled:'રદ', foodEyebrow:'જનની ફૂડ ગાઇડ', foodTitle:'ગર્ભાવસ્થા માટે સરળ પોષણ', balancedTitle:'દરેક થાળી સંતુલિત બનાવો', hydrationTitle:'પાણી મહત્વનું છે', foodSafetyTitle:'ખાદ્ય સુરક્ષા પ્રથમ', carePlusMealTitle:'કેર+ ભોજન સહાય', openCarePlus:'કેર+ ખોલો' },
  pa: { careEyebrow:'ਨਿੱਜੀ ਕੇਅਰ ਟਾਈਮਲਾਈਨ', careTitle:'ਮੁਲਾਕਾਤਾਂ, ਸਕੈਨ ਅਤੇ ਫਾਲੋ-ਅੱਪ ਇੱਕ ਥਾਂ।', addCareEntry:'ਕੇਅਰ ਐਂਟਰੀ ਜੋੜੋ', editCareEntry:'ਕੇਅਰ ਐਂਟਰੀ ਸੋਧੋ', type:'ਕਿਸਮ', date:'ਤਾਰੀਖ', time:'ਸਮਾਂ', doctorProvider:'ਡਾਕਟਰ / ਪ੍ਰਦਾਤਾ', facility:'ਹਸਪਤਾਲ / ਕਲੀਨਿਕ / ਲੈਬ', purpose:'ਮਕਸਦ', questionsToAsk:'ਪੁੱਛਣ ਵਾਲੇ ਸਵਾਲ', onePerLine:'ਹਰ ਲਾਈਨ ਵਿੱਚ ਇੱਕ', status:'ਸਥਿਤੀ', notesAfterVisit:'ਮੁਲਾਕਾਤ ਤੋਂ ਬਾਅਦ ਨੋਟ', testsPrescribed:'ਦੱਸੇ ਟੈਸਟ / ਸਕੈਨ', cancel:'ਰੱਦ ਕਰੋ', save:'ਸੇਵ ਕਰੋ', timeline:'ਟਾਈਮਲਾਈਨ', noEntries:'ਹਾਲੇ ਕੋਈ ਐਂਟਰੀ ਨਹੀਂ।', scheduled:'ਨਿਯਤ', completed:'ਪੂਰਾ', cancelled:'ਰੱਦ', foodEyebrow:'ਜਨਨੀ ਫੂਡ ਗਾਈਡ', foodTitle:'ਗਰਭਾਵਸਥਾ ਲਈ ਸਧਾਰਣ ਪੋਸ਼ਣ', balancedTitle:'ਹਰ ਪਲੇਟ ਸੰਤੁਲਿਤ ਬਣਾਓ', hydrationTitle:'ਪਾਣੀ ਮਹੱਤਵਪੂਰਨ ਹੈ', foodSafetyTitle:'ਖੁਰਾਕ ਸੁਰੱਖਿਆ ਪਹਿਲਾਂ', carePlusMealTitle:'ਕੇਅਰ+ ਭੋਜਨ ਸਹਾਇਤਾ', openCarePlus:'ਕੇਅਰ+ ਖੋਲ੍ਹੋ' },
  or: { careEyebrow:'ବ୍ୟକ୍ତିଗତ କେୟାର ଟାଇମଲାଇନ୍', careTitle:'ଭିଜିଟ୍, ସ୍କାନ୍ ଏବଂ ଫଲୋ-ଅପ୍ ଏକ ସ୍ଥାନରେ।', addCareEntry:'କେୟାର ଏଣ୍ଟ୍ରି ଯୋଡନ୍ତୁ', editCareEntry:'କେୟାର ଏଣ୍ଟ୍ରି ସମ୍ପାଦନା କରନ୍ତୁ', type:'ପ୍ରକାର', date:'ତାରିଖ', time:'ସମୟ', status:'ସ୍ଥିତି', cancel:'ବାତିଲ୍', save:'ସେଭ୍', timeline:'ଟାଇମଲାଇନ୍', noEntries:'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଏଣ୍ଟ୍ରି ନାହିଁ।', foodEyebrow:'ଜନନୀ ଫୁଡ୍ ଗାଇଡ୍', foodTitle:'ଗର୍ଭାବସ୍ଥା ପାଇଁ ସରଳ ପୋଷଣ', balancedTitle:'ପ୍ରତ୍ୟେକ ପ୍ଲେଟ୍ ସମତୁଳିତ କରନ୍ତୁ', hydrationTitle:'ପାଣି ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ', foodSafetyTitle:'ଖାଦ୍ୟ ସୁରକ୍ଷା ପ୍ରଥମେ', carePlusMealTitle:'କେୟାର+ ଭୋଜନ ସହାୟତା', openCarePlus:'କେୟାର+ ଖୋଲନ୍ତୁ' },
  as: { careEyebrow:'ব্যক্তিগত কেয়াৰ টাইমলাইন', careTitle:'ভিজিট, স্কেন আৰু ফলো-আপ একে ঠাইত।', addCareEntry:'কেয়াৰ এণ্ট্রি যোগ কৰক', editCareEntry:'কেয়াৰ এণ্ট্রি সম্পাদনা কৰক', type:'ধৰণ', date:'তাৰিখ', time:'সময়', status:'অৱস্থা', cancel:'বাতিল', save:'সংৰক্ষণ', timeline:'টাইমলাইন', noEntries:'এতিয়াও কোনো এণ্ট্রি নাই।', foodEyebrow:'জননী ফুড গাইড', foodTitle:'গৰ্ভাৱস্থাৰ বাবে সহজ পুষ্টি', balancedTitle:'প্ৰতিখন প্লেট সুষম কৰক', hydrationTitle:'পানী গুৰুত্বপূৰ্ণ', foodSafetyTitle:'খাদ্য সুৰক্ষা প্ৰথমে', carePlusMealTitle:'কেয়াৰ+ আহাৰ সহায়তা', openCarePlus:'কেয়াৰ+ খোলক' },
  ur: { careEyebrow:'نجی نگہداشت ٹائم لائن', careTitle:'ملاقاتیں، اسکین اور فالو اپ ایک جگہ۔', addCareEntry:'نگہداشت اندراج شامل کریں', editCareEntry:'نگہداشت اندراج میں ترمیم کریں', type:'قسم', date:'تاریخ', time:'وقت', doctorProvider:'ڈاکٹر / فراہم کنندہ', facility:'ہسپتال / کلینک / لیب', purpose:'مقصد', questionsToAsk:'پوچھنے کے سوالات', onePerLine:'ہر لائن میں ایک', status:'حالت', notesAfterVisit:'ملاقات کے بعد نوٹس', testsPrescribed:'تجویز کردہ ٹیسٹ / اسکین', cancel:'منسوخ', save:'محفوظ کریں', timeline:'ٹائم لائن', noEntries:'ابھی کوئی اندراج نہیں۔', scheduled:'طے شدہ', completed:'مکمل', cancelled:'منسوخ', foodEyebrow:'جننی فوڈ گائیڈ', foodTitle:'حمل کے لیے سادہ غذائیت', balancedTitle:'ہر پلیٹ متوازن رکھیں', hydrationTitle:'پانی اہم ہے', foodSafetyTitle:'خوراک کی حفاظت پہلے', carePlusMealTitle:'کیر+ کھانے کی مدد', openCarePlus:'کیر+ کھولیں' },
  ne: { careEyebrow:'निजी हेरचाह टाइमलाइन', careTitle:'भेट, स्क्यान र फलो-अप एउटै ठाउँमा।', addCareEntry:'हेरचाह प्रविष्टि थप्नुहोस्', editCareEntry:'हेरचाह प्रविष्टि सम्पादन गर्नुहोस्', type:'प्रकार', date:'मिति', time:'समय', doctorProvider:'डाक्टर / प्रदायक', facility:'अस्पताल / क्लिनिक / ल्याब', purpose:'उद्देश्य', questionsToAsk:'सोध्ने प्रश्नहरू', onePerLine:'प्रति लाइन एक', status:'स्थिति', notesAfterVisit:'भेटपछि नोटहरू', testsPrescribed:'सुझाइएका परीक्षण / स्क्यान', cancel:'रद्द', save:'सेभ', timeline:'टाइमलाइन', noEntries:'अहिलेसम्म कुनै प्रविष्टि छैन।', scheduled:'निर्धारित', completed:'पूरा', cancelled:'रद्द', foodEyebrow:'जननी फूड गाइड', foodTitle:'गर्भावस्थाका लागि सरल पोषण', balancedTitle:'हरेक प्लेट सन्तुलित बनाउनुहोस्', hydrationTitle:'पानी महत्त्वपूर्ण छ', foodSafetyTitle:'खाद्य सुरक्षा पहिले', carePlusMealTitle:'केयर+ भोजन सहायता', openCarePlus:'केयर+ खोल्नुहोस्' },
};

export function careFoodT(localeCode: string, key: CareFoodKey): string {
  const normalized = normalizeLocaleCode(localeCode);
  const base = normalized.split('-')[0].toLowerCase();
  return packs[normalized]?.[key] ?? packs[base]?.[key] ?? en[key];
}
