import type { JananiLanguage } from '@/i18n';

const copy = {
  en: {
    pregnancyEyebrow:'MY PREGNANCY', pregnancyTitle:'A gentle guide through each trimester', firstTrimester:'First trimester', secondTrimester:'Second trimester', thirdTrimester:'Third trimester', weeks1:'Weeks 1–13', weeks2:'Weeks 14–27', weeks3:'Weeks 28–40+', openReminders:'Open my reminders',
    remindersEyebrow:'TODAY’S CARE', remindersTitle:'Gentle reminders', remindersOffline:'Showing saved care data. Changes marked taken or skipped will sync later.', remindersNote:'No scolding here. Janani simply helps the family remember and try again.', nothingToday:'Nothing scheduled today', nothingTodayBody:'Add medicines, hydration, appointments, or a custom care reminder.', addFirstReminder:'Add first reminder', paused:'Paused', skipped:'Skipped', skipToday:'Skip today', taken:'Taken', markTaken:'Mark taken', edit:'Edit', pause:'Pause', resume:'Resume', delete:'Delete',
    journalEyebrow:'PREGNANCY JOURNAL', journalTitle:'Little moments, safely kept', journalOffline:'Showing saved journal entries. Pending deletions will sync later.', journalPrivacy:'Every entry is private unless its author chooses to share it with the partner.', journalEmpty:'Your story begins here', journalEmptyBody:'Write about a feeling, a tiny milestone, a doctor visit, or something you want to remember years from now.', writeFirst:'Write first entry', pendingSync:'Pending sync', shared:'Shared', private:'Private', yourEntry:'Your entry', sharedByPartner:'Shared by your partner', editEntry:'Edit entry', deleteEntry:'Delete entry',
  },
  te: {
    pregnancyEyebrow:'నా గర్భధారణ', pregnancyTitle:'ప్రతి త్రైమాసికానికి మృదువైన మార్గదర్శి', firstTrimester:'మొదటి త్రైమాసికం', secondTrimester:'రెండో త్రైమాసికం', thirdTrimester:'మూడో త్రైమాసికం', weeks1:'1–13 వారాలు', weeks2:'14–27 వారాలు', weeks3:'28–40+ వారాలు', openReminders:'నా రిమైండర్లు తెరవండి',
    remindersEyebrow:'ఈరోజు సంరక్షణ', remindersTitle:'మృదువైన రిమైండర్లు', remindersOffline:'సేవ్ చేసిన సంరక్షణ డేటాను చూపిస్తున్నాం. తీసుకున్నది లేదా దాటవేసింది అని గుర్తించిన మార్పులు తర్వాత సింక్ అవుతాయి.', remindersNote:'ఇక్కడ మందలింపు లేదు. గుర్తుంచుకోవడానికి జనని కుటుంబానికి సహాయం చేస్తుంది.', nothingToday:'ఈ రోజు ఏదీ షెడ్యూల్ కాలేదు', nothingTodayBody:'మందులు, నీరు, అపాయింట్‌మెంట్లు లేదా కస్టమ్ రిమైండర్ జోడించండి.', addFirstReminder:'మొదటి రిమైండర్ జోడించండి', paused:'పాజ్ చేయబడింది', skipped:'దాటవేశారు', skipToday:'ఈ రోజు దాటవేయండి', taken:'తీసుకున్నారు', markTaken:'తీసుకున్నట్లు గుర్తించండి', edit:'సవరించండి', pause:'పాజ్', resume:'మళ్లీ ప్రారంభించండి', delete:'తొలగించండి',
    journalEyebrow:'గర్భధారణ జర్నల్', journalTitle:'చిన్న జ్ఞాపకాలు, సురక్షితంగా', journalOffline:'సేవ్ చేసిన జర్నల్ ఎంట్రీలను చూపిస్తున్నాం. పెండింగ్ తొలగింపులు తర్వాత సింక్ అవుతాయి.', journalPrivacy:'రచయిత భాగస్వామితో పంచుకోవాలని ఎంచుకోకపోతే ప్రతి ఎంట్రీ వ్యక్తిగతంగానే ఉంటుంది.', journalEmpty:'మీ కథ ఇక్కడ మొదలవుతుంది', journalEmptyBody:'ఒక భావన, చిన్న మైలురాయి, డాక్టర్ విజిట్ లేదా ఎన్నేళ్ల తర్వాత గుర్తుంచుకోవాలనుకున్న విషయం రాయండి.', writeFirst:'మొదటి ఎంట్రీ రాయండి', pendingSync:'సింక్ పెండింగ్', shared:'పంచుకున్నారు', private:'వ్యక్తిగతం', yourEntry:'మీ ఎంట్రీ', sharedByPartner:'మీ భాగస్వామి పంచుకున్నారు', editEntry:'ఎంట్రీ సవరించండి', deleteEntry:'ఎంట్రీ తొలగించండి',
  },
  hi: {
    pregnancyEyebrow:'मेरी गर्भावस्था', pregnancyTitle:'हर तिमाही के लिए एक सहज मार्गदर्शिका', firstTrimester:'पहली तिमाही', secondTrimester:'दूसरी तिमाही', thirdTrimester:'तीसरी तिमाही', weeks1:'सप्ताह 1–13', weeks2:'सप्ताह 14–27', weeks3:'सप्ताह 28–40+', openReminders:'मेरे रिमाइंडर खोलें',
    remindersEyebrow:'आज की देखभाल', remindersTitle:'सहज रिमाइंडर', remindersOffline:'सहेजा हुआ देखभाल डेटा दिखाया जा रहा है। लिए गए या छोड़े गए बदलाव बाद में सिंक होंगे।', remindersNote:'यहाँ डाँट नहीं है। जननी परिवार को याद रखने और फिर कोशिश करने में मदद करता है।', nothingToday:'आज कुछ निर्धारित नहीं है', nothingTodayBody:'दवाइयाँ, पानी, अपॉइंटमेंट या कस्टम रिमाइंडर जोड़ें।', addFirstReminder:'पहला रिमाइंडर जोड़ें', paused:'रुका हुआ', skipped:'छोड़ा गया', skipToday:'आज छोड़ें', taken:'लिया गया', markTaken:'लिया हुआ दर्ज करें', edit:'संपादित करें', pause:'रोकें', resume:'फिर शुरू करें', delete:'हटाएँ',
    journalEyebrow:'गर्भावस्था जर्नल', journalTitle:'छोटे पल, सुरक्षित रूप से संजोएँ', journalOffline:'सहेजी गई जर्नल प्रविष्टियाँ दिखाई जा रही हैं। लंबित हटाने बाद में सिंक होंगे।', journalPrivacy:'हर प्रविष्टि निजी है, जब तक उसका लेखक उसे साथी के साथ साझा न करे।', journalEmpty:'आपकी कहानी यहाँ से शुरू होती है', journalEmptyBody:'किसी भावना, छोटे पड़ाव, डॉक्टर विज़िट या वर्षों बाद याद रखने वाली बात के बारे में लिखें।', writeFirst:'पहली प्रविष्टि लिखें', pendingSync:'सिंक लंबित', shared:'साझा', private:'निजी', yourEntry:'आपकी प्रविष्टि', sharedByPartner:'आपके साथी ने साझा किया', editEntry:'प्रविष्टि संपादित करें', deleteEntry:'प्रविष्टि हटाएँ',
  },
} as const;

export type DailyCareKey = keyof typeof copy.en;
export function dailyCareText(language: JananiLanguage, key: DailyCareKey): string { return copy[language]?.[key] ?? copy.en[key]; }
