const en = {
  pregnancyEyebrow:'MY PREGNANCY', pregnancyTitle:'A gentle guide through each trimester', firstTrimester:'First trimester', secondTrimester:'Second trimester', thirdTrimester:'Third trimester', weeks1:'Weeks 1–13', weeks2:'Weeks 14–27', weeks3:'Weeks 28–40+', openReminders:'Open my reminders',
  remindersEyebrow:'TODAY’S CARE', remindersTitle:'Gentle reminders', remindersOffline:'Showing saved care data. Changes marked taken or skipped will sync later.', remindersNote:'No scolding here. Janani simply helps the family remember and try again.', nothingToday:'Nothing scheduled today', nothingTodayBody:'Add medicines, hydration, appointments, or a custom care reminder.', addFirstReminder:'Add first reminder', paused:'Paused', skipped:'Skipped', skipToday:'Skip today', taken:'Taken', markTaken:'Mark taken', edit:'Edit', pause:'Pause', resume:'Resume', delete:'Delete',
  journalEyebrow:'PREGNANCY JOURNAL', journalTitle:'Little moments, safely kept', journalOffline:'Showing saved journal entries. Pending deletions will sync later.', journalPrivacy:'Every entry is private unless its author chooses to share it with the partner.', journalEmpty:'Your story begins here', journalEmptyBody:'Write about a feeling, a tiny milestone, a doctor visit, or something you want to remember years from now.', writeFirst:'Write first entry', pendingSync:'Pending sync', shared:'Shared', private:'Private', yourEntry:'Your entry', sharedByPartner:'Shared by your partner', editEntry:'Edit entry', deleteEntry:'Delete entry',
} as const;

export type DailyCareKey = keyof typeof en;
type Pack = Partial<Record<DailyCareKey, string>>;

const packs: Record<string, Pack> = {
  te:{pregnancyEyebrow:'నా గర్భధారణ',pregnancyTitle:'ప్రతి త్రైమాసికానికి మృదువైన మార్గదర్శి',firstTrimester:'మొదటి త్రైమాసికం',secondTrimester:'రెండో త్రైమాసికం',thirdTrimester:'మూడో త్రైమాసికం',weeks1:'1–13 వారాలు',weeks2:'14–27 వారాలు',weeks3:'28–40+ వారాలు',openReminders:'నా రిమైండర్లు తెరవండి',remindersEyebrow:'ఈరోజు సంరక్షణ',remindersTitle:'మృదువైన రిమైండర్లు',nothingToday:'ఈ రోజు ఏదీ షెడ్యూల్ కాలేదు',addFirstReminder:'మొదటి రిమైండర్ జోడించండి',paused:'పాజ్ చేయబడింది',skipped:'దాటవేశారు',skipToday:'ఈ రోజు దాటవేయండి',taken:'తీసుకున్నారు',markTaken:'తీసుకున్నట్లు గుర్తించండి',edit:'సవరించండి',pause:'పాజ్',resume:'మళ్లీ ప్రారంభించండి',delete:'తొలగించండి',journalEyebrow:'గర్భధారణ జర్నల్',journalTitle:'చిన్న జ్ఞాపకాలు, సురక్షితంగా',journalEmpty:'మీ కథ ఇక్కడ మొదలవుతుంది',writeFirst:'మొదటి ఎంట్రీ రాయండి',pendingSync:'సింక్ పెండింగ్',shared:'పంచుకున్నారు',private:'వ్యక్తిగతం',yourEntry:'మీ ఎంట్రీ',sharedByPartner:'మీ భాగస్వామి పంచుకున్నారు',editEntry:'ఎంట్రీ సవరించండి',deleteEntry:'ఎంట్రీ తొలగించండి'},
  hi:{pregnancyEyebrow:'मेरी गर्भावस्था',pregnancyTitle:'हर तिमाही के लिए एक सहज मार्गदर्शिका',firstTrimester:'पहली तिमाही',secondTrimester:'दूसरी तिमाही',thirdTrimester:'तीसरी तिमाही',weeks1:'सप्ताह 1–13',weeks2:'सप्ताह 14–27',weeks3:'सप्ताह 28–40+',openReminders:'मेरे रिमाइंडर खोलें',remindersEyebrow:'आज की देखभाल',remindersTitle:'सहज रिमाइंडर',nothingToday:'आज कुछ निर्धारित नहीं है',addFirstReminder:'पहला रिमाइंडर जोड़ें',paused:'रुका हुआ',skipped:'छोड़ा गया',skipToday:'आज छोड़ें',taken:'लिया गया',markTaken:'लिया हुआ दर्ज करें',edit:'संपादित करें',pause:'रोकें',resume:'फिर शुरू करें',delete:'हटाएँ',journalEyebrow:'गर्भावस्था जर्नल',journalTitle:'छोटे पल, सुरक्षित रूप से संजोएँ',journalEmpty:'आपकी कहानी यहाँ से शुरू होती है',writeFirst:'पहली प्रविष्टि लिखें',pendingSync:'सिंक लंबित',shared:'साझा',private:'निजी',yourEntry:'आपकी प्रविष्टि',sharedByPartner:'आपके साथी ने साझा किया',editEntry:'प्रविष्टि संपादित करें',deleteEntry:'प्रविष्टि हटाएँ'},
  ta:{remindersEyebrow:'இன்றைய பராமரிப்பு',remindersTitle:'மென்மையான நினைவூட்டல்கள்',nothingToday:'இன்று எதுவும் திட்டமிடப்படவில்லை',addFirstReminder:'முதல் நினைவூட்டலைச் சேர்க்கவும்',paused:'இடைநிறுத்தப்பட்டது',skipped:'தவிர்க்கப்பட்டது',skipToday:'இன்று தவிர்க்கவும்',taken:'எடுத்தது',markTaken:'எடுத்ததாக குறிக்கவும்',edit:'திருத்து',pause:'இடைநிறுத்து',resume:'தொடரவும்',delete:'நீக்கு',journalEyebrow:'கர்ப்பகால நாள்குறிப்பு',journalTitle:'சிறிய தருணங்கள், பாதுகாப்பாக',journalEmpty:'உங்கள் கதை இங்கே தொடங்குகிறது',writeFirst:'முதல் பதிவை எழுதவும்',shared:'பகிரப்பட்டது',private:'தனிப்பட்டது',yourEntry:'உங்கள் பதிவு'},
  kn:{remindersEyebrow:'ಇಂದಿನ ಕಾಳಜಿ',remindersTitle:'ಸೌಮ್ಯ ಜ್ಞಾಪನೆಗಳು',nothingToday:'ಇಂದು ಏನೂ ನಿಗದಿಯಾಗಿಲ್ಲ',addFirstReminder:'ಮೊದಲ ಜ್ಞಾಪನೆ ಸೇರಿಸಿ',paused:'ವಿರಾಮ',skipped:'ಬಿಟ್ಟಿದೆ',skipToday:'ಇಂದು ಬಿಡಿ',taken:'ತೆಗೆದುಕೊಂಡಿದೆ',markTaken:'ತೆಗೆದುಕೊಂಡಂತೆ ಗುರುತಿಸಿ',edit:'ತಿದ್ದು',pause:'ವಿರಾಮ',resume:'ಮುಂದುವರಿಸಿ',delete:'ಅಳಿಸಿ',journalEyebrow:'ಗರ್ಭಧಾರಣೆ ಜರ್ನಲ್',journalTitle:'ಚಿಕ್ಕ ಕ್ಷಣಗಳು, ಸುರಕ್ಷಿತವಾಗಿ',journalEmpty:'ನಿಮ್ಮ ಕಥೆ ಇಲ್ಲಿ ಆರಂಭವಾಗುತ್ತದೆ',writeFirst:'ಮೊದಲ ದಾಖಲೆಯನ್ನು ಬರೆಯಿರಿ',shared:'ಹಂಚಲಾಗಿದೆ',private:'ಖಾಸಗಿ',yourEntry:'ನಿಮ್ಮ ದಾಖಲೆ'},
  ml:{remindersEyebrow:'ഇന്നത്തെ പരിചരണം',remindersTitle:'സൗമ്യ ഓർമ്മപ്പെടുത്തലുകൾ',nothingToday:'ഇന്ന് ഒന്നും ഷെഡ്യൂൾ ചെയ്തിട്ടില്ല',addFirstReminder:'ആദ്യ ഓർമ്മപ്പെടുത്തൽ ചേർക്കുക',paused:'താൽക്കാലികമായി നിർത്തി',skipped:'ഒഴിവാക്കി',skipToday:'ഇന്ന് ഒഴിവാക്കുക',taken:'എടുത്തു',markTaken:'എടുത്തതായി അടയാളപ്പെടുത്തുക',edit:'തിരുത്തുക',pause:'നിർത്തുക',resume:'തുടരുക',delete:'നീക്കുക',journalEyebrow:'ഗർഭകാല ജേർണൽ',journalTitle:'ചെറിയ നിമിഷങ്ങൾ, സുരക്ഷിതമായി',journalEmpty:'നിങ്ങളുടെ കഥ ഇവിടെ തുടങ്ങുന്നു',writeFirst:'ആദ്യ കുറിപ്പ് എഴുതുക',shared:'പങ്കിട്ടത്',private:'സ്വകാര്യ',yourEntry:'നിങ്ങളുടെ കുറിപ്പ്'},
  mr:{remindersEyebrow:'आजची काळजी',remindersTitle:'सौम्य स्मरणपत्रे',nothingToday:'आज काहीही नियोजित नाही',addFirstReminder:'पहिले स्मरणपत्र जोडा',paused:'थांबवले',skipped:'वगळले',skipToday:'आज वगळा',taken:'घेतले',markTaken:'घेतले म्हणून नोंदवा',edit:'संपादित करा',pause:'थांबवा',resume:'पुन्हा सुरू करा',delete:'हटवा',journalEyebrow:'गर्भावस्था जर्नल',journalTitle:'छोटे क्षण, सुरक्षित जतन',journalEmpty:'तुमची कथा इथून सुरू होते',writeFirst:'पहिली नोंद लिहा',shared:'शेअर केले',private:'खाजगी',yourEntry:'तुमची नोंद'},
  bn:{remindersEyebrow:'আজকের যত্ন',remindersTitle:'সহজ রিমাইন্ডার',nothingToday:'আজ কিছু নির্ধারিত নেই',addFirstReminder:'প্রথম রিমাইন্ডার যোগ করুন',paused:'বিরত',skipped:'এড়ানো হয়েছে',skipToday:'আজ এড়িয়ে যান',taken:'নেওয়া হয়েছে',markTaken:'নেওয়া হয়েছে হিসেবে চিহ্নিত করুন',edit:'সম্পাদনা',pause:'বিরতি',resume:'চালু করুন',delete:'মুছুন',journalEyebrow:'গর্ভাবস্থা জার্নাল',journalTitle:'ছোট মুহূর্ত, নিরাপদে রাখা',journalEmpty:'আপনার গল্প এখানে শুরু',writeFirst:'প্রথম লেখা লিখুন',shared:'শেয়ার করা',private:'ব্যক্তিগত',yourEntry:'আপনার লেখা'},
  gu:{remindersEyebrow:'આજની કાળજી',remindersTitle:'હળવા રિમાઇન્ડર્સ',nothingToday:'આજે કંઈ નક્કી નથી',addFirstReminder:'પહેલું રિમાઇન્ડર ઉમેરો',paused:'વિરામ',skipped:'છોડ્યું',skipToday:'આજે છોડો',taken:'લીધું',markTaken:'લીધું તરીકે ચિહ્નિત કરો',edit:'સંપાદિત કરો',pause:'વિરામ',resume:'ફરી શરૂ કરો',delete:'કાઢી નાખો',journalEyebrow:'ગર્ભાવસ્થા જર્નલ',journalTitle:'નાની ક્ષણો, સુરક્ષિત રીતે',journalEmpty:'તમારી વાર્તા અહીંથી શરૂ થાય છે',writeFirst:'પ્રથમ નોંધ લખો',shared:'શેર કરેલું',private:'ખાનગી',yourEntry:'તમારી નોંધ'},
  pa:{remindersEyebrow:'ਅੱਜ ਦੀ ਦੇਖਭਾਲ',remindersTitle:'ਨਰਮ ਯਾਦ ਦਿਹਾਣੀਆਂ',nothingToday:'ਅੱਜ ਕੁਝ ਨਿਰਧਾਰਤ ਨਹੀਂ',addFirstReminder:'ਪਹਿਲੀ ਯਾਦ ਦਿਹਾਣੀ ਜੋੜੋ',paused:'ਰੋਕਿਆ',skipped:'ਛੱਡਿਆ',skipToday:'ਅੱਜ ਛੱਡੋ',taken:'ਲਿਆ',markTaken:'ਲਿਆ ਹੋਇਆ ਦਰਜ ਕਰੋ',edit:'ਸੋਧੋ',pause:'ਰੋਕੋ',resume:'ਮੁੜ ਚਲਾਓ',delete:'ਮਿਟਾਓ',journalEyebrow:'ਗਰਭ ਅਵਸਥਾ ਜਰਨਲ',journalTitle:'ਛੋਟੇ ਪਲ, ਸੁਰੱਖਿਅਤ',journalEmpty:'ਤੁਹਾਡੀ ਕਹਾਣੀ ਇੱਥੇ ਸ਼ੁਰੂ ਹੁੰਦੀ ਹੈ',writeFirst:'ਪਹਿਲੀ ਐਂਟਰੀ ਲਿਖੋ',shared:'ਸਾਂਝੀ',private:'ਨਿੱਜੀ',yourEntry:'ਤੁਹਾਡੀ ਐਂਟਰੀ'},
  ur:{remindersEyebrow:'آج کی دیکھ بھال',remindersTitle:'نرم یاد دہانیاں',nothingToday:'آج کچھ مقرر نہیں',addFirstReminder:'پہلی یاد دہانی شامل کریں',paused:'روکا گیا',skipped:'چھوڑ دیا',skipToday:'آج چھوڑ دیں',taken:'لیا گیا',markTaken:'لیا ہوا نشان زد کریں',edit:'ترمیم',pause:'روکیں',resume:'دوبارہ شروع کریں',delete:'حذف کریں',journalEyebrow:'حمل کی ڈائری',journalTitle:'چھوٹے لمحات، محفوظ',journalEmpty:'آپ کی کہانی یہاں سے شروع ہوتی ہے',writeFirst:'پہلی تحریر لکھیں',shared:'شیئر کیا گیا',private:'نجی',yourEntry:'آپ کی تحریر'},
  ne:{remindersEyebrow:'आजको हेरचाह',remindersTitle:'सहज रिमाइन्डर',nothingToday:'आज केही तय गरिएको छैन',addFirstReminder:'पहिलो रिमाइन्डर थप्नुहोस्',paused:'रोकिएको',skipped:'छोडिएको',skipToday:'आज छोड्नुहोस्',taken:'लिइयो',markTaken:'लिएको भनेर चिन्ह लगाउनुहोस्',edit:'सम्पादन',pause:'रोक्नुहोस्',resume:'फेरि सुरु गर्नुहोस्',delete:'मेटाउनुहोस्',journalEyebrow:'गर्भावस्था जर्नल',journalTitle:'साना क्षणहरू, सुरक्षित',journalEmpty:'तपाईंको कथा यहाँबाट सुरु हुन्छ',writeFirst:'पहिलो प्रविष्टि लेख्नुहोस्',shared:'साझा गरिएको',private:'निजी',yourEntry:'तपाईंको प्रविष्टि'},
};

export function dailyCareText(localeCode: string, key: DailyCareKey): string {
  const normalized = localeCode.trim().replace('_','-').toLowerCase();
  const base = normalized.split('-')[0];
  return packs[normalized]?.[key] ?? packs[base]?.[key] ?? en[key];
}
