import type { MessageKey } from '@/i18n';

export type GlobalUiPack = Partial<Record<MessageKey, string>>;

// Ordinary, non-clinical UI only. These packs are machine-assisted first-pass copy and
// intentionally do not contain urgent medical, medication, legal, privacy, or destructive-action wording.
export const GLOBAL_UI_PACKS: Record<string, GlobalUiPack> = {
  ta: {
    homeGreetingMother: 'இன்று எப்படி உணர்கிறீர்கள்?', homeGreetingPartner: 'சிறிய அக்கறையும் பெரிய அர்த்தம் தரும்.', toolsTitle: 'உங்கள் ஜனனி கருவிகள்', todayWithJanani: 'இன்று ஜனனியுடன்', week: 'வாரம்', day: 'நாள்', pregnancyGuide: 'கர்ப்பகால வழிகாட்டி', healthGuide: 'ஆரோக்கிய வழிகாட்டி', healthProfile: 'ஆரோக்கிய சுயவிவரம்', healthTracker: 'ஆரோக்கிய கண்காணிப்பு', careTimeline: 'பராமரிப்பு காலவரிசை', careContext: 'பராமரிப்பு விவரங்கள்', carePlus: 'ஜனனி கேர்+', reminders: 'நினைவூட்டல்கள்', foodGuide: 'உணவு வழிகாட்டி', journal: 'நாள்குறிப்பு', thinkingOfYou: 'உங்களை நினைக்கிறேன்', safetyPrivacy: 'பாதுகாப்பு & தனியுரிமை', settings: 'அமைப்புகள்', signIn: 'உள்நுழைக', createAccount: 'என் கணக்கை உருவாக்கு', mother: 'தாய்', partner: 'துணை', yourName: 'உங்கள் பெயர்', familyName: 'குடும்பப் பெயர்', languageRegion: 'மொழி & பகுதி', saveCareContext: 'பராமரிப்பு விவரங்களைச் சேமிக்கவும்', saved: 'சேமிக்கப்பட்டது',
  },
  kn: {
    homeGreetingMother: 'ಇಂದು ನೀವು ಹೇಗಿದ್ದೀರಿ?', homeGreetingPartner: 'ಸ್ವಲ್ಪ ಕಾಳಜಿಯೂ ಬಹಳ ಅರ್ಥ ಹೊಂದಿದೆ.', toolsTitle: 'ನಿಮ್ಮ ಜನನಿ ಸಾಧನಗಳು', todayWithJanani: 'ಇಂದು ಜನನಿಯೊಂದಿಗೆ', week: 'ವಾರ', day: 'ದಿನ', pregnancyGuide: 'ಗರ್ಭಧಾರಣೆ ಮಾರ್ಗದರ್ಶಿ', healthGuide: 'ಆರೋಗ್ಯ ಮಾರ್ಗದರ್ಶಿ', healthProfile: 'ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್', healthTracker: 'ಆರೋಗ್ಯ ಟ್ರ್ಯಾಕರ್', careTimeline: 'ಕೇರ್ ಟೈಮ್‌ಲೈನ್', careContext: 'ಕೇರ್ ವಿವರಗಳು', carePlus: 'ಜನನಿ ಕೇರ್+', reminders: 'ಜ್ಞಾಪನೆಗಳು', foodGuide: 'ಆಹಾರ ಮಾರ್ಗದರ್ಶಿ', journal: 'ಜರ್ನಲ್', thinkingOfYou: 'ನಿನ್ನ ನೆನಪು', safetyPrivacy: 'ಸುರಕ್ಷತೆ & ಗೌಪ್ಯತೆ', settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು', signIn: 'ಸೈನ್ ಇನ್', createAccount: 'ನನ್ನ ಖಾತೆ ರಚಿಸಿ', mother: 'ತಾಯಿ', partner: 'ಸಂಗಾತಿ', yourName: 'ನಿಮ್ಮ ಹೆಸರು', familyName: 'ಕುಟುಂಬದ ಹೆಸರು', languageRegion: 'ಭಾಷೆ & ಪ್ರದೇಶ', saveCareContext: 'ಕೇರ್ ವಿವರಗಳನ್ನು ಉಳಿಸಿ', saved: 'ಉಳಿಸಲಾಗಿದೆ',
  },
  ml: {
    homeGreetingMother: 'ഇന്ന് നിങ്ങൾക്ക് എങ്ങനെ തോന്നുന്നു?', homeGreetingPartner: 'ചെറിയൊരു കരുതലും വലിയ അർത്ഥമുണ്ട്.', toolsTitle: 'നിങ്ങളുടെ ജനനി ഉപകരണങ്ങൾ', todayWithJanani: 'ഇന്ന് ജനനിയോടെ', week: 'ആഴ്ച', day: 'ദിവസം', pregnancyGuide: 'ഗർഭകാല മാർഗ്ഗനിർദ്ദേശം', healthGuide: 'ആരോഗ്യ മാർഗ്ഗനിർദ്ദേശം', healthProfile: 'ആരോഗ്യ പ്രൊഫൈൽ', healthTracker: 'ആരോഗ്യ ട്രാക്കർ', careTimeline: 'പരിചരണ സമയരേഖ', careContext: 'പരിചരണ വിവരങ്ങൾ', carePlus: 'ജനനി കെയർ+', reminders: 'ഓർമ്മപ്പെടുത്തലുകൾ', foodGuide: 'ഭക്ഷണ മാർഗ്ഗനിർദ്ദേശം', journal: 'ജേർണൽ', thinkingOfYou: 'നിന്നെ ഓർക്കുന്നു', safetyPrivacy: 'സുരക്ഷ & സ്വകാര്യത', settings: 'ക്രമീകരണങ്ങൾ', signIn: 'സൈൻ ഇൻ', createAccount: 'എന്റെ അക്കൗണ്ട് സൃഷ്ടിക്കുക', mother: 'അമ്മ', partner: 'പങ്കാളി', yourName: 'നിങ്ങളുടെ പേര്', familyName: 'കുടുംബത്തിന്റെ പേര്', languageRegion: 'ഭാഷ & പ്രദേശം', saveCareContext: 'പരിചരണ വിവരങ്ങൾ സേവ് ചെയ്യുക', saved: 'സേവ് ചെയ്തു',
  },
  mr: {
    homeGreetingMother: 'आज तुम्हाला कसे वाटत आहे?', homeGreetingPartner: 'थोडीशी काळजीही खूप महत्त्वाची असते.', toolsTitle: 'तुमची जननी साधने', todayWithJanani: 'आज जननीसोबत', week: 'आठवडा', day: 'दिवस', pregnancyGuide: 'गर्भावस्था मार्गदर्शक', healthGuide: 'आरोग्य मार्गदर्शक', healthProfile: 'आरोग्य प्रोफाइल', healthTracker: 'आरोग्य ट्रॅकर', careTimeline: 'केअर टाइमलाइन', careContext: 'केअर संदर्भ', carePlus: 'जननी केअर+', reminders: 'स्मरणपत्रे', foodGuide: 'आहार मार्गदर्शक', journal: 'जर्नल', thinkingOfYou: 'तुझी आठवण', safetyPrivacy: 'सुरक्षा आणि गोपनीयता', settings: 'सेटिंग्ज', signIn: 'साइन इन', createAccount: 'माझे खाते तयार करा', mother: 'आई', partner: 'जोडीदार', yourName: 'तुमचे नाव', familyName: 'कुटुंबाचे नाव', languageRegion: 'भाषा आणि प्रदेश', saveCareContext: 'केअर संदर्भ जतन करा', saved: 'जतन केले',
  },
  bn: {
    homeGreetingMother: 'আজ আপনি কেমন অনুভব করছেন?', homeGreetingPartner: 'একটু যত্নও অনেক কিছু বোঝায়।', toolsTitle: 'আপনার জননী টুলস', todayWithJanani: 'আজ জননীর সঙ্গে', week: 'সপ্তাহ', day: 'দিন', pregnancyGuide: 'গর্ভাবস্থা নির্দেশিকা', healthGuide: 'স্বাস্থ্য নির্দেশিকা', healthProfile: 'স্বাস্থ্য প্রোফাইল', healthTracker: 'স্বাস্থ্য ট্র্যাকার', careTimeline: 'কেয়ার টাইমলাইন', careContext: 'কেয়ার তথ্য', carePlus: 'জননী কেয়ার+', reminders: 'রিমাইন্ডার', foodGuide: 'খাদ্য নির্দেশিকা', journal: 'জার্নাল', thinkingOfYou: 'তোমার কথা ভাবছি', safetyPrivacy: 'নিরাপত্তা ও গোপনীয়তা', settings: 'সেটিংস', signIn: 'সাইন ইন', createAccount: 'আমার অ্যাকাউন্ট তৈরি করুন', mother: 'মা', partner: 'সঙ্গী', yourName: 'আপনার নাম', familyName: 'পরিবারের নাম', languageRegion: 'ভাষা ও অঞ্চল', saveCareContext: 'কেয়ার তথ্য সংরক্ষণ করুন', saved: 'সংরক্ষিত',
  },
  gu: {
    homeGreetingMother: 'આજે તમને કેમ લાગે છે?', homeGreetingPartner: 'થોડી કાળજી પણ ઘણું કહે છે.', toolsTitle: 'તમારા જનની સાધનો', todayWithJanani: 'આજે જનની સાથે', week: 'અઠવાડિયું', day: 'દિવસ', pregnancyGuide: 'ગર્ભાવસ્થા માર્ગદર્શિકા', healthGuide: 'આરોગ્ય માર્ગદર્શિકા', healthProfile: 'આરોગ્ય પ્રોફાઇલ', healthTracker: 'આરોગ્ય ટ્રેકર', careTimeline: 'કેર સમયરેખા', careContext: 'કેર વિગતો', carePlus: 'જનની કેર+', reminders: 'યાદ અપાવણીઓ', foodGuide: 'આહાર માર્ગદર્શિકા', journal: 'જર્નલ', thinkingOfYou: 'તમારી યાદ આવે છે', safetyPrivacy: 'સુરક્ષા અને ગોપનીયતા', settings: 'સેટિંગ્સ', signIn: 'સાઇન ઇન', createAccount: 'મારું ખાતું બનાવો', mother: 'માતા', partner: 'સાથી', yourName: 'તમારું નામ', familyName: 'કુટુંબનું નામ', languageRegion: 'ભાષા અને પ્રદેશ', saveCareContext: 'કેર વિગતો સાચવો', saved: 'સાચવાયું',
  },
  pa: {
    homeGreetingMother: 'ਅੱਜ ਤੁਸੀਂ ਕਿਵੇਂ ਮਹਿਸੂਸ ਕਰ ਰਹੇ ਹੋ?', homeGreetingPartner: 'ਥੋੜ੍ਹੀ ਜਿਹੀ ਦੇਖਭਾਲ ਵੀ ਬਹੁਤ ਮਾਇਨੇ ਰੱਖਦੀ ਹੈ।', toolsTitle: 'ਤੁਹਾਡੇ ਜਨਨੀ ਟੂਲ', todayWithJanani: 'ਅੱਜ ਜਨਨੀ ਨਾਲ', week: 'ਹਫ਼ਤਾ', day: 'ਦਿਨ', pregnancyGuide: 'ਗਰਭਾਵਸਥਾ ਮਾਰਗਦਰਸ਼ਿਕਾ', healthGuide: 'ਸਿਹਤ ਮਾਰਗਦਰਸ਼ਿਕਾ', healthProfile: 'ਸਿਹਤ ਪ੍ਰੋਫ਼ਾਈਲ', healthTracker: 'ਸਿਹਤ ਟ੍ਰੈਕਰ', careTimeline: 'ਕੇਅਰ ਟਾਈਮਲਾਈਨ', careContext: 'ਕੇਅਰ ਵੇਰਵੇ', carePlus: 'ਜਨਨੀ ਕੇਅਰ+', reminders: 'ਯਾਦ ਦਿਹਾਣੀਆਂ', foodGuide: 'ਖਾਣ-ਪੀਣ ਮਾਰਗਦਰਸ਼ਿਕਾ', journal: 'ਜਰਨਲ', thinkingOfYou: 'ਤੁਹਾਡੀ ਯਾਦ', safetyPrivacy: 'ਸੁਰੱਖਿਆ ਅਤੇ ਪਰਦੇਦਾਰੀ', settings: 'ਸੈਟਿੰਗਾਂ', signIn: 'ਸਾਈਨ ਇਨ', createAccount: 'ਮੇਰਾ ਖਾਤਾ ਬਣਾਓ', mother: 'ਮਾਂ', partner: 'ਸਾਥੀ', yourName: 'ਤੁਹਾਡਾ ਨਾਮ', familyName: 'ਪਰਿਵਾਰ ਦਾ ਨਾਮ', languageRegion: 'ਭਾਸ਼ਾ ਅਤੇ ਖੇਤਰ', saveCareContext: 'ਕੇਅਰ ਵੇਰਵੇ ਸੰਭਾਲੋ', saved: 'ਸੰਭਾਲਿਆ ਗਿਆ',
  },
  or: {
    homeGreetingMother: 'ଆଜି ଆପଣ କେମିତି ଅନୁଭବ କରୁଛନ୍ତି?', toolsTitle: 'ଆପଣଙ୍କ ଜନନୀ ସାଧନ', week: 'ସପ୍ତାହ', day: 'ଦିନ', pregnancyGuide: 'ଗର୍ଭାବସ୍ଥା ମାର୍ଗଦର୍ଶିକା', healthGuide: 'ସ୍ୱାସ୍ଥ୍ୟ ମାର୍ଗଦର୍ଶିକା', healthProfile: 'ସ୍ୱାସ୍ଥ୍ୟ ପ୍ରୋଫାଇଲ', healthTracker: 'ସ୍ୱାସ୍ଥ୍ୟ ଟ୍ରାକର', careTimeline: 'କେୟାର ଟାଇମଲାଇନ', carePlus: 'ଜନନୀ କେୟାର+', reminders: 'ସ୍ମରଣିକା', foodGuide: 'ଖାଦ୍ୟ ମାର୍ଗଦର୍ଶିକା', journal: 'ଜର୍ନାଲ', safetyPrivacy: 'ସୁରକ୍ଷା ଓ ଗୋପନୀୟତା', settings: 'ସେଟିଂସ୍', signIn: 'ସାଇନ୍ ଇନ୍', mother: 'ମା', partner: 'ସହଭାଗୀ', languageRegion: 'ଭାଷା ଓ ଅଞ୍ଚଳ', saved: 'ସଂରକ୍ଷିତ',
  },
  as: {
    homeGreetingMother: 'আজি আপোনাৰ কেনে লাগিছে?', toolsTitle: 'আপোনাৰ জননী সঁজুলি', week: 'সপ্তাহ', day: 'দিন', pregnancyGuide: 'গৰ্ভাৱস্থা পথপ্ৰদৰ্শক', healthGuide: 'স্বাস্থ্য পথপ্ৰদৰ্শক', healthProfile: 'স্বাস্থ্য প্ৰফাইল', healthTracker: 'স্বাস্থ্য ট্ৰেকাৰ', careTimeline: 'কেয়াৰ টাইমলাইন', carePlus: 'জননী কেয়াৰ+', reminders: 'সোঁৱৰাই দিয়া', foodGuide: 'খাদ্য পথপ্ৰদৰ্শক', journal: 'জাৰ্নেল', safetyPrivacy: 'সুৰক্ষা আৰু গোপনীয়তা', settings: 'ছেটিংছ', signIn: 'ছাইন ইন', mother: 'মা', partner: 'সঙ্গী', languageRegion: 'ভাষা আৰু অঞ্চল', saved: 'সংৰক্ষিত',
  },
  ur: {
    homeGreetingMother: 'آج آپ کیسا محسوس کر رہی ہیں؟', homeGreetingPartner: 'تھوڑی سی دیکھ بھال بھی بہت معنی رکھتی ہے۔', toolsTitle: 'آپ کے جننی ٹولز', todayWithJanani: 'آج جننی کے ساتھ', week: 'ہفتہ', day: 'دن', pregnancyGuide: 'حمل کی رہنمائی', healthGuide: 'صحت کی رہنمائی', healthProfile: 'صحت پروفائل', healthTracker: 'صحت ٹریکر', careTimeline: 'کیئر ٹائم لائن', careContext: 'کیئر معلومات', carePlus: 'جننی کیئر+', reminders: 'یاد دہانیاں', foodGuide: 'خوراک کی رہنمائی', journal: 'جرنل', thinkingOfYou: 'آپ کی یاد', safetyPrivacy: 'حفاظت اور رازداری', settings: 'سیٹنگز', signIn: 'سائن اِن', createAccount: 'میرا اکاؤنٹ بنائیں', mother: 'ماں', partner: 'ساتھی', yourName: 'آپ کا نام', familyName: 'خاندان کا نام', languageRegion: 'زبان اور علاقہ', saveCareContext: 'کیئر معلومات محفوظ کریں', saved: 'محفوظ ہوگیا',
  },
  ne: {
    homeGreetingMother: 'आज तपाईंलाई कस्तो महसुस भइरहेको छ?', toolsTitle: 'तपाईंका जननी उपकरणहरू', todayWithJanani: 'आज जननीसँग', week: 'हप्ता', day: 'दिन', pregnancyGuide: 'गर्भावस्था मार्गदर्शिका', healthGuide: 'स्वास्थ्य मार्गदर्शिका', healthProfile: 'स्वास्थ्य प्रोफाइल', healthTracker: 'स्वास्थ्य ट्र्याकर', careTimeline: 'केयर टाइमलाइन', careContext: 'केयर विवरण', carePlus: 'जननी केयर+', reminders: 'रिमाइन्डरहरू', foodGuide: 'खाना मार्गदर्शिका', journal: 'जर्नल', safetyPrivacy: 'सुरक्षा र गोपनीयता', settings: 'सेटिङहरू', signIn: 'साइन इन', createAccount: 'मेरो खाता बनाउनुहोस्', mother: 'आमा', partner: 'साथी', yourName: 'तपाईंको नाम', familyName: 'परिवारको नाम', languageRegion: 'भाषा र क्षेत्र', saveCareContext: 'केयर विवरण सुरक्षित गर्नुहोस्', saved: 'सुरक्षित भयो',
  },
};
