import { healthT, type HealthMessageKey } from '@/i18n/health';
import { normalizeLocaleCode, uiTranslationLanguageFor } from '@/i18n/localeRegistry';

const packs: Record<string, Partial<Record<HealthMessageKey, string>>> = {
  ta: { profileEyebrow:'தனிப்பட்ட ஆரோக்கிய சுயவிவரம்', profileTitle:'உங்கள் பராமரிப்பு தகவல்கள் ஒரே இடத்தில்.', pregnancyBody:'கர்ப்பம் & உடல்', currentWeight:'தற்போதைய எடை (kg)', pregnancy:'கர்ப்பம்', activityLevel:'செயற்பாட்டு நிலை', foodPreferences:'உணவு விருப்பங்கள்', foodPattern:'உணவு முறை', cuisinePreferences:'சமையல் விருப்பங்கள்', healthConditions:'உடல்நிலை தகவல்கள்', clinicianInstructions:'மருத்துவர் வழிமுறைகள்', saveHealthProfile:'ஆரோக்கிய சுயவிவரத்தை சேமிக்கவும்', trackerEyebrow:'தனிப்பட்ட ஆரோக்கிய கண்காணிப்பு', trackerTitle:'உங்கள் பதிவுகளை ஒரே இடத்தில் வைத்திருங்கள்.', weight:'எடை', bloodPressure:'ரத்த அழுத்தம்', glucose:'குளுக்கோஸ்', labResult:'ஆய்வக முடிவு', symptom:'அறிகுறி', add:'சேர்க்க', saveEntry:'பதிவை சேமிக்கவும்', recentEntries:'சமீபத்திய பதிவுகள்', noEntries:'இன்னும் பதிவுகள் இல்லை.' },
  kn: { profileEyebrow:'ಖಾಸಗಿ ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್', profileTitle:'ನಿಮ್ಮ ಆರೈಕೆ ಮಾಹಿತಿಯನ್ನು ಒಂದೇ ಕಡೆ ಇಡಿ.', pregnancyBody:'ಗರ್ಭಧಾರಣೆ & ದೇಹ', currentWeight:'ಪ್ರಸ್ತುತ ತೂಕ (kg)', pregnancy:'ಗರ್ಭಧಾರಣೆ', activityLevel:'ಚಟುವಟಿಕೆ ಮಟ್ಟ', foodPreferences:'ಆಹಾರ ಆದ್ಯತೆಗಳು', foodPattern:'ಆಹಾರ ಮಾದರಿ', healthConditions:'ಆರೋಗ್ಯ ಸ್ಥಿತಿಗಳು', clinicianInstructions:'ವೈದ್ಯರ ಸೂಚನೆಗಳು', saveHealthProfile:'ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ', trackerEyebrow:'ಖಾಸಗಿ ಆರೋಗ್ಯ ಟ್ರ್ಯಾಕರ್', trackerTitle:'ನಿಮ್ಮ ದಾಖಲಾತಿಗಳನ್ನು ಒಂದೇ ಕಡೆ ಇಡಿ.', weight:'ತೂಕ', bloodPressure:'ರಕ್ತದೊತ್ತಡ', glucose:'ಗ್ಲೂಕೋಸ್', labResult:'ಲ್ಯಾಬ್ ಫಲಿತಾಂಶ', symptom:'ಲಕ್ಷಣ', add:'ಸೇರಿಸಿ', saveEntry:'ದಾಖಲೆ ಉಳಿಸಿ', recentEntries:'ಇತ್ತೀಚಿನ ದಾಖಲೆಗಳು', noEntries:'ಇನ್ನೂ ದಾಖಲೆಗಳಿಲ್ಲ.' },
  ml: { profileEyebrow:'സ്വകാര്യ ആരോഗ്യ പ്രൊഫൈൽ', profileTitle:'നിങ്ങളുടെ പരിചരണ വിവരങ്ങൾ ഒരിടത്ത്.', pregnancyBody:'ഗർഭകാലം & ശരീരം', currentWeight:'നിലവിലെ ഭാരം (kg)', pregnancy:'ഗർഭകാലം', activityLevel:'പ്രവർത്തന നില', foodPreferences:'ഭക്ഷണ ഇഷ്ടങ്ങൾ', foodPattern:'ഭക്ഷണ രീതി', healthConditions:'ആരോഗ്യ അവസ്ഥകൾ', clinicianInstructions:'ഡോക്ടറുടെ നിർദ്ദേശങ്ങൾ', saveHealthProfile:'ആരോഗ്യ പ്രൊഫൈൽ സേവ് ചെയ്യുക', trackerEyebrow:'സ്വകാര്യ ആരോഗ്യ ട്രാക്കർ', trackerTitle:'നിങ്ങളുടെ രേഖകൾ ഒരിടത്ത് സൂക്ഷിക്കുക.', weight:'ഭാരം', bloodPressure:'രക്തസമ്മർദ്ദം', glucose:'ഗ്ലൂക്കോസ്', labResult:'ലാബ് ഫലം', symptom:'ലക്ഷണം', add:'ചേർക്കുക', saveEntry:'എൻട്രി സേവ് ചെയ്യുക', recentEntries:'സമീപകാല എൻട്രികൾ', noEntries:'ഇനിയും എൻട്രികളില്ല.' },
  mr: { profileEyebrow:'खाजगी आरोग्य प्रोफाइल', profileTitle:'तुमची काळजीविषयक माहिती एकाच ठिकाणी.', pregnancyBody:'गर्भावस्था आणि शरीर', currentWeight:'सध्याचे वजन (kg)', pregnancy:'गर्भावस्था', activityLevel:'क्रियाशीलता स्तर', foodPreferences:'आहार पसंती', foodPattern:'आहार पद्धत', healthConditions:'आरोग्य स्थिती', clinicianInstructions:'डॉक्टरांच्या सूचना', saveHealthProfile:'आरोग्य प्रोफाइल जतन करा', trackerEyebrow:'खाजगी आरोग्य ट्रॅकर', trackerTitle:'तुमच्या नोंदी एकाच ठिकाणी ठेवा.', weight:'वजन', bloodPressure:'रक्तदाब', glucose:'ग्लुकोज', labResult:'लॅब निकाल', symptom:'लक्षण', add:'जोडा', saveEntry:'नोंद जतन करा', recentEntries:'अलीकडील नोंदी', noEntries:'अजून नोंदी नाहीत.' },
  bn: { profileEyebrow:'ব্যক্তিগত স্বাস্থ্য প্রোফাইল', profileTitle:'আপনার যত্নের তথ্য এক জায়গায় রাখুন।', pregnancyBody:'গর্ভাবস্থা ও শরীর', currentWeight:'বর্তমান ওজন (kg)', pregnancy:'গর্ভাবস্থা', activityLevel:'কার্যকলাপের স্তর', foodPreferences:'খাবারের পছন্দ', foodPattern:'খাদ্যাভ্যাস', healthConditions:'স্বাস্থ্য অবস্থা', clinicianInstructions:'ডাক্তারের নির্দেশনা', saveHealthProfile:'স্বাস্থ্য প্রোফাইল সংরক্ষণ করুন', trackerEyebrow:'ব্যক্তিগত স্বাস্থ্য ট্র্যাকার', trackerTitle:'আপনার রেকর্ড এক জায়গায় রাখুন।', weight:'ওজন', bloodPressure:'রক্তচাপ', glucose:'গ্লুকোজ', labResult:'ল্যাব ফলাফল', symptom:'উপসর্গ', add:'যোগ করুন', saveEntry:'এন্ট্রি সংরক্ষণ করুন', recentEntries:'সাম্প্রতিক এন্ট্রি', noEntries:'এখনও কোনো এন্ট্রি নেই।' },
  gu: { profileEyebrow:'ખાનગી આરોગ્ય પ્રોફાઇલ', profileTitle:'તમારી કાળજીની માહિતી એક જ જગ્યાએ રાખો.', pregnancyBody:'ગર્ભાવસ્થા અને શરીર', currentWeight:'હાલનું વજન (kg)', pregnancy:'ગર્ભાવસ્થા', activityLevel:'પ્રવૃત્તિ સ્તર', foodPreferences:'ખોરાક પસંદગીઓ', healthConditions:'આરોગ્ય સ્થિતિઓ', clinicianInstructions:'ડૉક્ટરની સૂચનાઓ', saveHealthProfile:'આરોગ્ય પ્રોફાઇલ સાચવો', trackerEyebrow:'ખાનગી આરોગ્ય ટ્રેકર', trackerTitle:'તમારી નોંધો એક જ જગ્યાએ રાખો.', weight:'વજન', bloodPressure:'બ્લડ પ્રેશર', glucose:'ગ્લુકોઝ', labResult:'લેબ પરિણામ', symptom:'લક્ષણ', add:'ઉમેરો', saveEntry:'નોંધ સાચવો', recentEntries:'તાજેતરની નોંધો', noEntries:'હજુ કોઈ નોંધ નથી.' },
  pa: { profileEyebrow:'ਨਿੱਜੀ ਸਿਹਤ ਪ੍ਰੋਫਾਈਲ', profileTitle:'ਆਪਣੀ ਦੇਖਭਾਲ ਦੀ ਜਾਣਕਾਰੀ ਇਕੱਠੀ ਰੱਖੋ।', pregnancyBody:'ਗਰਭਾਵਸਥਾ ਅਤੇ ਸਰੀਰ', currentWeight:'ਮੌਜੂਦਾ ਵਜ਼ਨ (kg)', pregnancy:'ਗਰਭਾਵਸਥਾ', activityLevel:'ਸਰਗਰਮੀ ਪੱਧਰ', foodPreferences:'ਖਾਣੇ ਦੀਆਂ ਪਸੰਦਾਂ', healthConditions:'ਸਿਹਤ ਹਾਲਤਾਂ', clinicianInstructions:'ਡਾਕਟਰ ਦੀਆਂ ਹਦਾਇਤਾਂ', saveHealthProfile:'ਸਿਹਤ ਪ੍ਰੋਫਾਈਲ ਸੰਭਾਲੋ', trackerEyebrow:'ਨਿੱਜੀ ਸਿਹਤ ਟ੍ਰੈਕਰ', trackerTitle:'ਆਪਣੀਆਂ ਰਿਕਾਰਡਿੰਗਾਂ ਇਕੱਠੀਆਂ ਰੱਖੋ।', weight:'ਵਜ਼ਨ', bloodPressure:'ਬਲੱਡ ਪ੍ਰੈਸ਼ਰ', glucose:'ਗਲੂਕੋਜ਼', labResult:'ਲੈਬ ਨਤੀਜਾ', symptom:'ਲੱਛਣ', add:'ਸ਼ਾਮਲ ਕਰੋ', saveEntry:'ਐਂਟਰੀ ਸੰਭਾਲੋ', recentEntries:'ਹਾਲੀਆ ਐਂਟਰੀਆਂ', noEntries:'ਹਾਲੇ ਕੋਈ ਐਂਟਰੀ ਨਹੀਂ।' },
  ur: { profileEyebrow:'نجی صحت پروفائل', profileTitle:'اپنی نگہداشت کی معلومات ایک جگہ رکھیں۔', pregnancyBody:'حمل اور جسم', currentWeight:'موجودہ وزن (kg)', pregnancy:'حمل', activityLevel:'سرگرمی کی سطح', foodPreferences:'خوراک کی ترجیحات', healthConditions:'صحت کی حالتیں', clinicianInstructions:'ڈاکٹر کی ہدایات', saveHealthProfile:'صحت پروفائل محفوظ کریں', trackerEyebrow:'نجی صحت ٹریکر', trackerTitle:'اپنی ریڈنگز ایک جگہ رکھیں۔', weight:'وزن', bloodPressure:'بلڈ پریشر', glucose:'گلوکوز', labResult:'لیب نتیجہ', symptom:'علامت', add:'شامل کریں', saveEntry:'اندراج محفوظ کریں', recentEntries:'حالیہ اندراجات', noEntries:'ابھی کوئی اندراج نہیں۔' },
  ne: { profileEyebrow:'निजी स्वास्थ्य प्रोफाइल', profileTitle:'तपाईंको हेरचाह जानकारी एकै ठाउँमा राख्नुहोस्।', pregnancyBody:'गर्भावस्था र शरीर', currentWeight:'हालको तौल (kg)', pregnancy:'गर्भावस्था', activityLevel:'गतिविधि स्तर', foodPreferences:'खानाको प्राथमिकता', healthConditions:'स्वास्थ्य अवस्थाहरू', clinicianInstructions:'चिकित्सकका निर्देशन', saveHealthProfile:'स्वास्थ्य प्रोफाइल सुरक्षित गर्नुहोस्', trackerEyebrow:'निजी स्वास्थ्य ट्र्याकर', trackerTitle:'तपाईंका रेकर्डहरू एकै ठाउँमा राख्नुहोस्।', weight:'तौल', bloodPressure:'रक्तचाप', glucose:'ग्लुकोज', labResult:'ल्याब नतिजा', symptom:'लक्षण', add:'थप्नुहोस्', saveEntry:'रेकर्ड सुरक्षित गर्नुहोस्', recentEntries:'हालका रेकर्ड', noEntries:'अहिलेसम्म कुनै रेकर्ड छैन।' },
};

export function healthGlobalT(localeCode: string, key: HealthMessageKey): string {
  const normalized = normalizeLocaleCode(localeCode);
  const base = normalized.split('-')[0].toLowerCase();
  const value = packs[normalized]?.[key] ?? packs[base]?.[key];
  if (value) return value;
  return healthT(uiTranslationLanguageFor(normalized), key);
}
