import type { MessageKey } from '@/i18n';

export type InternationalUiPack = Partial<Record<MessageKey, string>>;

// Machine-assisted ordinary UI only. No urgent medical, medication, legal,
// privacy, emergency, or destructive-action wording belongs in these packs.
export const INTERNATIONAL_UI_PACKS: Record<string, InternationalUiPack> = {
  es: { homeGreetingMother:'¿Cómo te sientes hoy?', homeGreetingPartner:'Un pequeño gesto de cuidado significa mucho.', toolsTitle:'Tus herramientas de Janani', todayWithJanani:'Hoy con Janani', week:'Semana', day:'Día', pregnancyGuide:'Guía del embarazo', healthGuide:'Guía de salud', healthProfile:'Perfil de salud', healthTracker:'Seguimiento de salud', careTimeline:'Cronología de cuidados', careContext:'Contexto de cuidados', carePlus:'Janani Care+', reminders:'Recordatorios', foodGuide:'Guía de alimentación', journal:'Diario', thinkingOfYou:'Pensando en ti', safetyPrivacy:'Seguridad y privacidad', settings:'Ajustes', signIn:'Iniciar sesión', createAccount:'Crear mi cuenta', mother:'Madre', partner:'Pareja', yourName:'Tu nombre', familyName:'Nombre de la familia', languageRegion:'Idioma y región', saveCareContext:'Guardar contexto de cuidados', saved:'Guardado' },
  pt: { homeGreetingMother:'Como você está se sentindo hoje?', homeGreetingPartner:'Um pequeno gesto de cuidado significa muito.', toolsTitle:'Suas ferramentas Janani', todayWithJanani:'Hoje com Janani', week:'Semana', day:'Dia', pregnancyGuide:'Guia da gravidez', healthGuide:'Guia de saúde', healthProfile:'Perfil de saúde', healthTracker:'Acompanhamento de saúde', careTimeline:'Linha do tempo de cuidados', careContext:'Contexto de cuidados', carePlus:'Janani Care+', reminders:'Lembretes', foodGuide:'Guia alimentar', journal:'Diário', thinkingOfYou:'Pensando em você', safetyPrivacy:'Segurança e privacidade', settings:'Configurações', signIn:'Entrar', createAccount:'Criar minha conta', mother:'Mãe', partner:'Parceiro', yourName:'Seu nome', familyName:'Nome da família', languageRegion:'Idioma e região', saveCareContext:'Salvar contexto de cuidados', saved:'Salvo' },
  fr: { homeGreetingMother:'Comment vous sentez-vous aujourd’hui ?', homeGreetingPartner:'Une petite attention compte beaucoup.', toolsTitle:'Vos outils Janani', todayWithJanani:'Aujourd’hui avec Janani', week:'Semaine', day:'Jour', pregnancyGuide:'Guide de grossesse', healthGuide:'Guide santé', healthProfile:'Profil santé', healthTracker:'Suivi santé', careTimeline:'Chronologie des soins', careContext:'Contexte de soins', carePlus:'Janani Care+', reminders:'Rappels', foodGuide:'Guide alimentaire', journal:'Journal', thinkingOfYou:'Je pense à toi', safetyPrivacy:'Sécurité et confidentialité', settings:'Paramètres', signIn:'Se connecter', createAccount:'Créer mon compte', mother:'Mère', partner:'Partenaire', yourName:'Votre nom', familyName:'Nom de famille', languageRegion:'Langue et région', saveCareContext:'Enregistrer le contexte de soins', saved:'Enregistré' },
  de: { homeGreetingMother:'Wie fühlst du dich heute?', homeGreetingPartner:'Eine kleine Geste der Fürsorge bedeutet viel.', toolsTitle:'Deine Janani-Werkzeuge', todayWithJanani:'Heute mit Janani', week:'Woche', day:'Tag', pregnancyGuide:'Schwangerschaftsratgeber', healthGuide:'Gesundheitsratgeber', healthProfile:'Gesundheitsprofil', healthTracker:'Gesundheitstracker', careTimeline:'Versorgungsverlauf', careContext:'Versorgungskontext', carePlus:'Janani Care+', reminders:'Erinnerungen', foodGuide:'Ernährungsratgeber', journal:'Tagebuch', thinkingOfYou:'Ich denke an dich', safetyPrivacy:'Sicherheit & Datenschutz', settings:'Einstellungen', signIn:'Anmelden', createAccount:'Mein Konto erstellen', mother:'Mutter', partner:'Partner', yourName:'Dein Name', familyName:'Familienname', languageRegion:'Sprache & Region', saveCareContext:'Versorgungskontext speichern', saved:'Gespeichert' },
  ar: { homeGreetingMother:'كيف تشعرين اليوم؟', homeGreetingPartner:'لفتة صغيرة من الاهتمام تعني الكثير.', toolsTitle:'أدوات جاناني الخاصة بك', todayWithJanani:'اليوم مع جاناني', week:'الأسبوع', day:'اليوم', pregnancyGuide:'دليل الحمل', healthGuide:'دليل الصحة', healthProfile:'الملف الصحي', healthTracker:'متابعة الصحة', careTimeline:'الخط الزمني للرعاية', careContext:'سياق الرعاية', carePlus:'جاناني كير+', reminders:'التذكيرات', foodGuide:'دليل الغذاء', journal:'اليوميات', thinkingOfYou:'أفكر بك', safetyPrivacy:'السلامة والخصوصية', settings:'الإعدادات', signIn:'تسجيل الدخول', createAccount:'إنشاء حسابي', mother:'الأم', partner:'الشريك', yourName:'اسمك', familyName:'اسم العائلة', languageRegion:'اللغة والمنطقة', saveCareContext:'حفظ سياق الرعاية', saved:'تم الحفظ' },
  id: { homeGreetingMother:'Bagaimana perasaan Anda hari ini?', homeGreetingPartner:'Perhatian kecil bisa sangat berarti.', toolsTitle:'Alat Janani Anda', todayWithJanani:'Hari ini bersama Janani', week:'Minggu', day:'Hari', pregnancyGuide:'Panduan kehamilan', healthGuide:'Panduan kesehatan', healthProfile:'Profil kesehatan', healthTracker:'Pelacak kesehatan', careTimeline:'Linimasa perawatan', careContext:'Konteks perawatan', carePlus:'Janani Care+', reminders:'Pengingat', foodGuide:'Panduan makanan', journal:'Jurnal', thinkingOfYou:'Memikirkanmu', safetyPrivacy:'Keamanan & privasi', settings:'Pengaturan', signIn:'Masuk', createAccount:'Buat akun saya', mother:'Ibu', partner:'Pasangan', yourName:'Nama Anda', familyName:'Nama keluarga', languageRegion:'Bahasa & wilayah', saveCareContext:'Simpan konteks perawatan', saved:'Tersimpan' },
  vi: { homeGreetingMother:'Hôm nay bạn cảm thấy thế nào?', homeGreetingPartner:'Một chút quan tâm cũng rất ý nghĩa.', toolsTitle:'Công cụ Janani của bạn', todayWithJanani:'Hôm nay cùng Janani', week:'Tuần', day:'Ngày', pregnancyGuide:'Hướng dẫn thai kỳ', healthGuide:'Hướng dẫn sức khỏe', healthProfile:'Hồ sơ sức khỏe', healthTracker:'Theo dõi sức khỏe', careTimeline:'Dòng thời gian chăm sóc', careContext:'Bối cảnh chăm sóc', carePlus:'Janani Care+', reminders:'Nhắc nhở', foodGuide:'Hướng dẫn dinh dưỡng', journal:'Nhật ký', thinkingOfYou:'Đang nghĩ về bạn', safetyPrivacy:'An toàn & riêng tư', settings:'Cài đặt', signIn:'Đăng nhập', createAccount:'Tạo tài khoản', mother:'Mẹ', partner:'Bạn đời', yourName:'Tên của bạn', familyName:'Tên gia đình', languageRegion:'Ngôn ngữ & khu vực', saveCareContext:'Lưu bối cảnh chăm sóc', saved:'Đã lưu' },
  th: { homeGreetingMother:'วันนี้คุณรู้สึกอย่างไร?', homeGreetingPartner:'ความใส่ใจเล็กๆ ก็มีความหมายมาก', toolsTitle:'เครื่องมือ Janani ของคุณ', todayWithJanani:'วันนี้กับ Janani', week:'สัปดาห์', day:'วัน', pregnancyGuide:'คู่มือการตั้งครรภ์', healthGuide:'คู่มือสุขภาพ', healthProfile:'โปรไฟล์สุขภาพ', healthTracker:'ติดตามสุขภาพ', careTimeline:'ไทม์ไลน์การดูแล', careContext:'บริบทการดูแล', carePlus:'Janani Care+', reminders:'การแจ้งเตือน', foodGuide:'คู่มืออาหาร', journal:'บันทึก', thinkingOfYou:'คิดถึงคุณ', safetyPrivacy:'ความปลอดภัยและความเป็นส่วนตัว', settings:'การตั้งค่า', signIn:'เข้าสู่ระบบ', createAccount:'สร้างบัญชีของฉัน', mother:'แม่', partner:'คู่ชีวิต', yourName:'ชื่อของคุณ', familyName:'ชื่อครอบครัว', languageRegion:'ภาษาและภูมิภาค', saveCareContext:'บันทึกบริบทการดูแล', saved:'บันทึกแล้ว' },
  'zh-CN': { homeGreetingMother:'今天感觉怎么样？', homeGreetingPartner:'一点点关心也很有意义。', toolsTitle:'你的 Janani 工具', todayWithJanani:'今天与 Janani', week:'周', day:'天', pregnancyGuide:'孕期指南', healthGuide:'健康指南', healthProfile:'健康档案', healthTracker:'健康追踪', careTimeline:'护理时间线', careContext:'护理信息', carePlus:'Janani Care+', reminders:'提醒', foodGuide:'饮食指南', journal:'日记', thinkingOfYou:'想念你', safetyPrivacy:'安全与隐私', settings:'设置', signIn:'登录', createAccount:'创建我的账户', mother:'妈妈', partner:'伴侣', yourName:'你的名字', familyName:'家庭名称', languageRegion:'语言和地区', saveCareContext:'保存护理信息', saved:'已保存' },
  'zh-TW': { homeGreetingMother:'今天感覺怎麼樣？', homeGreetingPartner:'一點點關心也很有意義。', toolsTitle:'你的 Janani 工具', todayWithJanani:'今天與 Janani', week:'週', day:'天', pregnancyGuide:'孕期指南', healthGuide:'健康指南', healthProfile:'健康檔案', healthTracker:'健康追蹤', careTimeline:'照護時間線', careContext:'照護資訊', carePlus:'Janani Care+', reminders:'提醒', foodGuide:'飲食指南', journal:'日記', thinkingOfYou:'想念你', safetyPrivacy:'安全與隱私', settings:'設定', signIn:'登入', createAccount:'建立我的帳戶', mother:'媽媽', partner:'伴侶', yourName:'你的名字', familyName:'家庭名稱', languageRegion:'語言和地區', saveCareContext:'儲存照護資訊', saved:'已儲存' },
  ja: { homeGreetingMother:'今日はどんな気分ですか？', homeGreetingPartner:'小さな気づかいにも大きな意味があります。', toolsTitle:'Janani のツール', todayWithJanani:'今日の Janani', week:'週', day:'日', pregnancyGuide:'妊娠ガイド', healthGuide:'健康ガイド', healthProfile:'健康プロフィール', healthTracker:'健康トラッカー', careTimeline:'ケアタイムライン', careContext:'ケア情報', carePlus:'Janani Care+', reminders:'リマインダー', foodGuide:'食事ガイド', journal:'ジャーナル', thinkingOfYou:'あなたを想っています', safetyPrivacy:'安全とプライバシー', settings:'設定', signIn:'ログイン', createAccount:'アカウントを作成', mother:'母', partner:'パートナー', yourName:'お名前', familyName:'家族名', languageRegion:'言語と地域', saveCareContext:'ケア情報を保存', saved:'保存済み' },
  ko: { homeGreetingMother:'오늘 기분이 어떠세요?', homeGreetingPartner:'작은 배려도 큰 의미가 있어요.', toolsTitle:'Janani 도구', todayWithJanani:'오늘의 Janani', week:'주', day:'일', pregnancyGuide:'임신 가이드', healthGuide:'건강 가이드', healthProfile:'건강 프로필', healthTracker:'건강 추적', careTimeline:'케어 타임라인', careContext:'케어 정보', carePlus:'Janani Care+', reminders:'알림', foodGuide:'식사 가이드', journal:'저널', thinkingOfYou:'당신을 생각해요', safetyPrivacy:'안전 및 개인정보', settings:'설정', signIn:'로그인', createAccount:'계정 만들기', mother:'엄마', partner:'파트너', yourName:'이름', familyName:'가족 이름', languageRegion:'언어 및 지역', saveCareContext:'케어 정보 저장', saved:'저장됨' },
  ru: { homeGreetingMother:'Как вы себя чувствуете сегодня?', homeGreetingPartner:'Даже небольшой знак заботы много значит.', toolsTitle:'Ваши инструменты Janani', todayWithJanani:'Сегодня с Janani', week:'Неделя', day:'День', pregnancyGuide:'Гид по беременности', healthGuide:'Гид по здоровью', healthProfile:'Профиль здоровья', healthTracker:'Трекер здоровья', careTimeline:'Хронология ухода', careContext:'Контекст ухода', carePlus:'Janani Care+', reminders:'Напоминания', foodGuide:'Гид по питанию', journal:'Дневник', thinkingOfYou:'Думаю о тебе', safetyPrivacy:'Безопасность и конфиденциальность', settings:'Настройки', signIn:'Войти', createAccount:'Создать аккаунт', mother:'Мама', partner:'Партнёр', yourName:'Ваше имя', familyName:'Название семьи', languageRegion:'Язык и регион', saveCareContext:'Сохранить контекст ухода', saved:'Сохранено' },
};
