import { normalizeLocaleCode } from '@/i18n/localeRegistry';
import { readGlobalUiLocale } from '@/i18n/uiLocale';

export type SystemCopy = {
  medicineNotificationTitle: string;
  medicineNotificationBody: string;
  careNotificationTitle: string;
  careNotificationBody: string;
  week: string;
  days: string;
  familyFallback: string;
  upcomingReminders: string;
  noMedicine: string;
  noAppointment: string;
  partnerWaiting: string;
  sendWarmth: string;
  babyMessages: string[];
  wellnessMessages: string[];
  dailyJourney: (week: number) => string;
  openJourney: string;
  widgetTodayTitle: string;
  widgetMedicineTitle: string;
  widgetLoveTitle: string;
  widgetAppointmentTitle: string;
  widgetWellnessTitle: string;
  widgetCareFallback: string;
  widgetMedicineFallback: string;
  widgetAppointmentFallback: string;
  widgetBabyFallback: string;
  widgetWellnessFallback: string;
  signedOutFamily: string;
  privateCare: string;
  openMedicines: string;
  openAppointments: string;
  openJanani: string;
  privatePregnancy: string;
  openWellness: string;
};

const en: SystemCopy = {
  medicineNotificationTitle:'💊 Medicine time', medicineNotificationBody:'It’s time for your scheduled medicine. Open Janani to view the private reminder.', careNotificationTitle:'A gentle Janani reminder', careNotificationBody:'Open Janani to view today’s private care reminder.',
  week:'Week', days:'days', familyFallback:'Our little family', upcomingReminders:'Open Janani for upcoming reminders', noMedicine:'No medicine due soon', noAppointment:'No appointment scheduled', partnerWaiting:'A little heart from your partner is waiting 💗', sendWarmth:'Send a little warmth 💗',
  babyMessages:['Your little journey is growing day by day.','Tiny changes are happening every day.','Another week of growing together.'], wellnessMessages:['Hydrate gently, eat regularly, and make room for rest.','A balanced plate and a little movement can support your day.','Small meals, enough fluids, and good rest are meaningful care.'],
  dailyJourney:(week)=>`You are ${week} weeks into this journey. Be gentle with yourself today.`, openJourney:'Open Janani for your pregnancy journey.',
  widgetTodayTitle:'Janani Today', widgetMedicineTitle:'Next medicine', widgetLoveTitle:'Thinking of you', widgetAppointmentTitle:'Next appointment', widgetWellnessTitle:'Daily wellness 🌿', widgetCareFallback:"Open Janani for today's care", widgetMedicineFallback:'No medicine due soon', widgetAppointmentFallback:'No appointment scheduled', widgetBabyFallback:"Open Janani for this week's journey", widgetWellnessFallback:'Eat gently, hydrate, and rest when your body asks.',
  signedOutFamily:'Sign in or link a family', privateCare:'Your care details are private', openMedicines:'Open Janani to view medicines', openAppointments:'Open Janani to view appointments', openJanani:'Open Janani', privatePregnancy:'Your pregnancy journey stays private', openWellness:'Open Janani for daily wellness',
};

const copy: Record<string, Partial<SystemCopy>> = {
  en,
  te:{medicineNotificationTitle:'💊 మందు సమయం',medicineNotificationBody:'మీరు షెడ్యూల్ చేసిన మందు సమయం వచ్చింది. వ్యక్తిగత రిమైండర్ చూడటానికి జనని తెరవండి.',careNotificationTitle:'జనని నుంచి మృదువైన గుర్తు',careNotificationBody:'ఈ రోజు మీ వ్యక్తిగత సంరక్షణ రిమైండర్ చూడటానికి జనని తెరవండి.',week:'వారం',days:'రోజులు',familyFallback:'మన చిన్న కుటుంబం',upcomingReminders:'రాబోయే రిమైండర్ల కోసం జనని తెరవండి',noMedicine:'త్వరలో తీసుకోవాల్సిన మందు లేదు',noAppointment:'అపాయింట్‌మెంట్ షెడ్యూల్ కాలేదు',partnerWaiting:'మీ భాగస్వామి నుంచి చిన్న హృదయం ఎదురుచూస్తోంది 💗',sendWarmth:'కొంచెం ప్రేమను పంపండి 💗',widgetTodayTitle:'ఈ రోజు జనని',widgetMedicineTitle:'తర్వాతి మందు',widgetLoveTitle:'నిన్ను గుర్తు చేసుకుంటున్నాను',widgetAppointmentTitle:'తర్వాతి అపాయింట్‌మెంట్',widgetWellnessTitle:'రోజువారీ వెల్‌నెస్ 🌿',signedOutFamily:'సైన్ ఇన్ చేయండి లేదా కుటుంబాన్ని లింక్ చేయండి',privateCare:'మీ సంరక్షణ వివరాలు వ్యక్తిగతం',openJanani:'జనని తెరవండి'},
  hi:{medicineNotificationTitle:'💊 दवा का समय',medicineNotificationBody:'आपकी तय की गई दवा का समय हो गया है। निजी रिमाइंडर देखने के लिए जननी खोलें।',careNotificationTitle:'जननी की एक हल्की याद',careNotificationBody:'आज का निजी केयर रिमाइंडर देखने के लिए जननी खोलें।',week:'सप्ताह',days:'दिन',familyFallback:'हमारा छोटा परिवार',upcomingReminders:'आने वाले रिमाइंडर देखने के लिए जननी खोलें',noMedicine:'अभी कोई दवा जल्द देय नहीं है',noAppointment:'कोई अपॉइंटमेंट तय नहीं है',partnerWaiting:'आपके साथी का एक छोटा-सा दिल आपका इंतज़ार कर रहा है 💗',sendWarmth:'थोड़ा अपनापन भेजें 💗',widgetTodayTitle:'आज जननी',widgetMedicineTitle:'अगली दवा',widgetLoveTitle:'आपकी याद',widgetAppointmentTitle:'अगला अपॉइंटमेंट',widgetWellnessTitle:'रोज़ का वेलनेस 🌿',signedOutFamily:'साइन इन करें या परिवार लिंक करें',privateCare:'आपकी देखभाल की जानकारी निजी है',openJanani:'जननी खोलें'},
  es:{medicineNotificationTitle:'💊 Hora de la medicina',medicineNotificationBody:'Es hora de tu medicina programada. Abre Janani para ver el recordatorio privado.',careNotificationTitle:'Un recordatorio amable de Janani',careNotificationBody:'Abre Janani para ver el recordatorio privado de hoy.',week:'Semana',days:'días',familyFallback:'Nuestra pequeña familia',upcomingReminders:'Abre Janani para ver próximos recordatorios',noMedicine:'No hay medicina próxima',noAppointment:'No hay cita programada',partnerWaiting:'Tu pareja te ha enviado un pequeño gesto de cariño 💗',sendWarmth:'Enviar un poco de cariño 💗',widgetTodayTitle:'Janani hoy',widgetMedicineTitle:'Próxima medicina',widgetLoveTitle:'Pensando en ti',widgetAppointmentTitle:'Próxima cita',widgetWellnessTitle:'Bienestar diario 🌿',signedOutFamily:'Inicia sesión o vincula una familia',privateCare:'Tus datos de cuidado son privados',openJanani:'Abrir Janani'},
  pt:{medicineNotificationTitle:'💊 Hora do remédio',medicineNotificationBody:'Está na hora do remédio programado. Abra o Janani para ver o lembrete privado.',careNotificationTitle:'Um lembrete gentil do Janani',careNotificationBody:'Abra o Janani para ver o lembrete privado de hoje.',week:'Semana',days:'dias',familyFallback:'Nossa pequena família',upcomingReminders:'Abra o Janani para ver os próximos lembretes',noMedicine:'Nenhum remédio próximo',noAppointment:'Nenhuma consulta agendada',partnerWaiting:'Um carinho do seu parceiro está esperando 💗',sendWarmth:'Enviar um carinho 💗',widgetTodayTitle:'Janani hoje',widgetMedicineTitle:'Próximo remédio',widgetLoveTitle:'Pensando em você',widgetAppointmentTitle:'Próxima consulta',widgetWellnessTitle:'Bem-estar diário 🌿',signedOutFamily:'Entre ou vincule uma família',privateCare:'Seus dados de cuidado são privados',openJanani:'Abrir Janani'},
  fr:{medicineNotificationTitle:'💊 Heure du médicament',medicineNotificationBody:'Il est temps de prendre le médicament programmé. Ouvrez Janani pour voir le rappel privé.',careNotificationTitle:'Un doux rappel Janani',careNotificationBody:'Ouvrez Janani pour voir le rappel privé du jour.',week:'Semaine',days:'jours',familyFallback:'Notre petite famille',upcomingReminders:'Ouvrez Janani pour les prochains rappels',noMedicine:'Aucun médicament prévu bientôt',noAppointment:'Aucun rendez-vous programmé',partnerWaiting:'Une petite attention de votre partenaire vous attend 💗',sendWarmth:'Envoyer une petite attention 💗',widgetTodayTitle:'Janani aujourd’hui',widgetMedicineTitle:'Prochain médicament',widgetLoveTitle:'Je pense à toi',widgetAppointmentTitle:'Prochain rendez-vous',widgetWellnessTitle:'Bien-être quotidien 🌿',signedOutFamily:'Connectez-vous ou liez une famille',privateCare:'Vos informations de soins sont privées',openJanani:'Ouvrir Janani'},
  de:{medicineNotificationTitle:'💊 Zeit für dein Medikament',medicineNotificationBody:'Es ist Zeit für dein geplantes Medikament. Öffne Janani für die private Erinnerung.',careNotificationTitle:'Eine sanfte Janani-Erinnerung',careNotificationBody:'Öffne Janani, um die private Erinnerung für heute zu sehen.',week:'Woche',days:'Tage',familyFallback:'Unsere kleine Familie',upcomingReminders:'Janani für kommende Erinnerungen öffnen',noMedicine:'Kein Medikament bald fällig',noAppointment:'Kein Termin geplant',partnerWaiting:'Eine kleine Nachricht von deinem Partner wartet 💗',sendWarmth:'Etwas Wärme senden 💗',widgetTodayTitle:'Janani heute',widgetMedicineTitle:'Nächstes Medikament',widgetLoveTitle:'Ich denke an dich',widgetAppointmentTitle:'Nächster Termin',widgetWellnessTitle:'Tägliches Wohlbefinden 🌿',signedOutFamily:'Anmelden oder Familie verknüpfen',privateCare:'Deine Gesundheitsdaten sind privat',openJanani:'Janani öffnen'},
  ar:{medicineNotificationTitle:'💊 وقت الدواء',medicineNotificationBody:'حان وقت الدواء المجدول. افتحي جاناني لعرض التذكير الخاص.',careNotificationTitle:'تذكير لطيف من جاناني',careNotificationBody:'افتحي جاناني لعرض تذكير الرعاية الخاص لليوم.',week:'الأسبوع',days:'أيام',familyFallback:'عائلتنا الصغيرة',upcomingReminders:'افتحي جاناني للتذكيرات القادمة',noMedicine:'لا يوجد دواء مستحق قريبًا',noAppointment:'لا يوجد موعد مجدول',partnerWaiting:'رسالة محبة صغيرة من شريكك بانتظارك 💗',sendWarmth:'أرسل لمسة محبة 💗',widgetTodayTitle:'جاناني اليوم',widgetMedicineTitle:'الدواء التالي',widgetLoveTitle:'أفكر بك',widgetAppointmentTitle:'الموعد التالي',widgetWellnessTitle:'العافية اليومية 🌿',signedOutFamily:'سجّل الدخول أو اربط عائلة',privateCare:'تفاصيل رعايتك خاصة',openJanani:'افتح جاناني'},
  id:{medicineNotificationTitle:'💊 Waktunya obat',medicineNotificationBody:'Saatnya obat yang dijadwalkan. Buka Janani untuk melihat pengingat pribadi.',careNotificationTitle:'Pengingat lembut dari Janani',careNotificationBody:'Buka Janani untuk melihat pengingat perawatan pribadi hari ini.',week:'Minggu',days:'hari',familyFallback:'Keluarga kecil kami',upcomingReminders:'Buka Janani untuk pengingat mendatang',noMedicine:'Tidak ada obat yang segera jatuh tempo',noAppointment:'Tidak ada janji terjadwal',partnerWaiting:'Ada perhatian kecil dari pasanganmu 💗',sendWarmth:'Kirim sedikit perhatian 💗',widgetTodayTitle:'Janani hari ini',widgetMedicineTitle:'Obat berikutnya',widgetLoveTitle:'Memikirkanmu',widgetAppointmentTitle:'Janji berikutnya',widgetWellnessTitle:'Kebugaran harian 🌿',signedOutFamily:'Masuk atau hubungkan keluarga',privateCare:'Detail perawatanmu bersifat pribadi',openJanani:'Buka Janani'},
  vi:{medicineNotificationTitle:'💊 Đến giờ uống thuốc',medicineNotificationBody:'Đã đến giờ dùng thuốc theo lịch. Mở Janani để xem lời nhắc riêng tư.',careNotificationTitle:'Một lời nhắc nhẹ nhàng từ Janani',careNotificationBody:'Mở Janani để xem lời nhắc chăm sóc riêng tư hôm nay.',week:'Tuần',days:'ngày',familyFallback:'Gia đình nhỏ của chúng ta',upcomingReminders:'Mở Janani để xem các lời nhắc sắp tới',noMedicine:'Không có thuốc sắp đến giờ',noAppointment:'Không có lịch hẹn',partnerWaiting:'Một lời nhắn ấm áp từ bạn đời đang chờ bạn 💗',sendWarmth:'Gửi một chút yêu thương 💗',widgetTodayTitle:'Janani hôm nay',widgetMedicineTitle:'Thuốc tiếp theo',widgetLoveTitle:'Đang nghĩ về bạn',widgetAppointmentTitle:'Lịch hẹn tiếp theo',widgetWellnessTitle:'Sức khỏe mỗi ngày 🌿',signedOutFamily:'Đăng nhập hoặc liên kết gia đình',privateCare:'Thông tin chăm sóc của bạn là riêng tư',openJanani:'Mở Janani'},
  th:{medicineNotificationTitle:'💊 ถึงเวลายา',medicineNotificationBody:'ถึงเวลายาตามกำหนดแล้ว เปิด Janani เพื่อดูการแจ้งเตือนส่วนตัว',careNotificationTitle:'การเตือนอย่างอ่อนโยนจาก Janani',careNotificationBody:'เปิด Janani เพื่อดูการเตือนการดูแลส่วนตัวของวันนี้',week:'สัปดาห์',days:'วัน',familyFallback:'ครอบครัวเล็กๆ ของเรา',upcomingReminders:'เปิด Janani เพื่อดูการเตือนที่กำลังจะมาถึง',noMedicine:'ยังไม่มียาที่ต้องใช้เร็วๆ นี้',noAppointment:'ยังไม่มีนัดหมาย',partnerWaiting:'มีความห่วงใยเล็กๆ จากคู่ของคุณรออยู่ 💗',sendWarmth:'ส่งความห่วงใยเล็กๆ 💗',widgetTodayTitle:'Janani วันนี้',widgetMedicineTitle:'ยาครั้งถัดไป',widgetLoveTitle:'คิดถึงคุณ',widgetAppointmentTitle:'นัดหมายถัดไป',widgetWellnessTitle:'สุขภาวะประจำวัน 🌿',signedOutFamily:'เข้าสู่ระบบหรือเชื่อมครอบครัว',privateCare:'รายละเอียดการดูแลของคุณเป็นส่วนตัว',openJanani:'เปิด Janani'},
  'zh-CN':{medicineNotificationTitle:'💊 用药时间',medicineNotificationBody:'到了计划用药时间。打开 Janani 查看私人提醒。',careNotificationTitle:'Janani 温柔提醒',careNotificationBody:'打开 Janani 查看今天的私人护理提醒。',week:'第',days:'天',familyFallback:'我们的小家庭',upcomingReminders:'打开 Janani 查看接下来的提醒',noMedicine:'近期没有用药提醒',noAppointment:'暂无预约',partnerWaiting:'伴侣送来了一点温暖 💗',sendWarmth:'送一点温暖 💗',widgetTodayTitle:'今日 Janani',widgetMedicineTitle:'下一次用药',widgetLoveTitle:'想念你',widgetAppointmentTitle:'下一次预约',widgetWellnessTitle:'每日健康 🌿',signedOutFamily:'登录或关联家庭',privateCare:'你的护理信息是私密的',openJanani:'打开 Janani'},
  'zh-TW':{medicineNotificationTitle:'💊 用藥時間',medicineNotificationBody:'到了預定用藥時間。開啟 Janani 查看私人提醒。',careNotificationTitle:'Janani 溫柔提醒',careNotificationBody:'開啟 Janani 查看今天的私人照護提醒。',week:'第',days:'天',familyFallback:'我們的小家庭',upcomingReminders:'開啟 Janani 查看接下來的提醒',noMedicine:'近期沒有用藥提醒',noAppointment:'暫無預約',partnerWaiting:'伴侶送來了一點溫暖 💗',sendWarmth:'送一點溫暖 💗',widgetTodayTitle:'今日 Janani',widgetMedicineTitle:'下一次用藥',widgetLoveTitle:'想念你',widgetAppointmentTitle:'下一次預約',widgetWellnessTitle:'每日健康 🌿',signedOutFamily:'登入或連結家庭',privateCare:'你的照護資訊是私密的',openJanani:'開啟 Janani'},
  ja:{medicineNotificationTitle:'💊 お薬の時間',medicineNotificationBody:'予定しているお薬の時間です。Janani を開いて非公開のリマインダーを確認してください。',careNotificationTitle:'Janani からやさしいお知らせ',careNotificationBody:'Janani を開いて今日の非公開ケアリマインダーを確認してください。',week:'週',days:'日',familyFallback:'私たちの小さな家族',upcomingReminders:'Janani で今後のリマインダーを見る',noMedicine:'間もなく予定されている薬はありません',noAppointment:'予定された予約はありません',partnerWaiting:'パートナーから小さな気づかいが届いています 💗',sendWarmth:'小さな気づかいを送る 💗',widgetTodayTitle:'今日の Janani',widgetMedicineTitle:'次のお薬',widgetLoveTitle:'あなたを想っています',widgetAppointmentTitle:'次の予約',widgetWellnessTitle:'毎日のウェルネス 🌿',signedOutFamily:'ログインまたは家族をリンク',privateCare:'ケア情報は非公開です',openJanani:'Janani を開く'},
  ko:{medicineNotificationTitle:'💊 약 복용 시간',medicineNotificationBody:'예정된 약 복용 시간입니다. Janani를 열어 비공개 알림을 확인하세요.',careNotificationTitle:'Janani의 부드러운 알림',careNotificationBody:'Janani를 열어 오늘의 비공개 케어 알림을 확인하세요.',week:'주',days:'일',familyFallback:'우리 작은 가족',upcomingReminders:'Janani에서 예정된 알림 보기',noMedicine:'곧 복용할 약이 없습니다',noAppointment:'예정된 일정이 없습니다',partnerWaiting:'파트너의 작은 마음이 기다리고 있어요 💗',sendWarmth:'작은 마음 보내기 💗',widgetTodayTitle:'오늘의 Janani',widgetMedicineTitle:'다음 약',widgetLoveTitle:'당신을 생각해요',widgetAppointmentTitle:'다음 일정',widgetWellnessTitle:'매일의 웰니스 🌿',signedOutFamily:'로그인하거나 가족 연결',privateCare:'케어 정보는 비공개입니다',openJanani:'Janani 열기'},
  ru:{medicineNotificationTitle:'💊 Время лекарства',medicineNotificationBody:'Пришло время запланированного лекарства. Откройте Janani, чтобы посмотреть личное напоминание.',careNotificationTitle:'Мягкое напоминание Janani',careNotificationBody:'Откройте Janani, чтобы посмотреть личное напоминание на сегодня.',week:'Неделя',days:'дней',familyFallback:'Наша маленькая семья',upcomingReminders:'Откройте Janani для будущих напоминаний',noMedicine:'Скоро нет запланированных лекарств',noAppointment:'Нет запланированных приёмов',partnerWaiting:'Небольшой знак заботы от партнёра ждёт вас 💗',sendWarmth:'Отправить немного тепла 💗',widgetTodayTitle:'Janani сегодня',widgetMedicineTitle:'Следующее лекарство',widgetLoveTitle:'Думаю о тебе',widgetAppointmentTitle:'Следующий приём',widgetWellnessTitle:'Ежедневное самочувствие 🌿',signedOutFamily:'Войдите или привяжите семью',privateCare:'Ваши данные о заботе приватны',openJanani:'Открыть Janani'},
};

export function systemCopy(localeCode: string): SystemCopy {
  const normalized=normalizeLocaleCode(localeCode);
  const base=normalized.split('-')[0].toLowerCase();
  const selected=copy[normalized] ?? copy[base] ?? {};
  return { ...en, ...selected } as SystemCopy;
}

export async function readSystemCopy(): Promise<SystemCopy> {
  return systemCopy(await readGlobalUiLocale());
}
