import { LegalDocumentScreen, type LegalSection } from '@/components/LegalDocumentScreen';

const sections: LegalSection[] = [
  { title:'1. Acceptance', paragraphs:['By using Janani, you agree to these Terms of Use and the Privacy Policy. Do not use the service if you do not agree.'] },
  { title:'2. Intended use', paragraphs:['Janani supports pregnancy journaling, care reminders, pregnancy-date calculations, and voluntary family connection. Its information is general and educational.'] },
  { title:'3. Medicines and care instructions', paragraphs:['You are responsible for entering accurate reminder information. Medicine name, dose, timing, and duration must follow instructions from a qualified clinician. A notification is not proof that medicine was taken or that a schedule is medically appropriate. Use an independent method for critical medical schedules.'] },
  { title:'4. Emergencies', paragraphs:['Do not rely on Janani during an emergency. For severe pain, heavy bleeding, breathing difficulty, fainting, seizures, reduced consciousness, or any urgent concern, contact local emergency services or a qualified maternity-care professional immediately.'] },
  { title:'5. Accounts and family access', paragraphs:['Keep account credentials and invite codes private. Link only with people you trust. Mothers may disconnect a linked partner, and partners may leave a family where those controls are available. Account deletion is permanent and has different effects for mother and partner accounts.'] },
  { title:'6. User content and conduct', paragraphs:['You remain responsible for journal entries, reminder content, and partner messages you create. Do not submit unlawful, abusive, rights-infringing, or malicious content. Do not add another person’s sensitive information without their permission.'] },
  { title:'7. Availability', paragraphs:['Notifications, realtime updates, offline synchronization, exports, widgets, Care+ features, and other connected services may be delayed or unavailable because of device settings, connectivity, operating-system restrictions, maintenance, provider outages, eligibility, or service changes. The service may change or be discontinued.'] },
  { title:'8. Janani Care+ and AI', paragraphs:['When Care+ is available, it provides supportive generated information based on relevant Janani context and the information you choose to save or submit. It cannot diagnose, prescribe, change medicine instructions, set medical targets, confirm that you or your baby are safe, or replace your maternity-care team.', 'Care+ availability, usage allowances, and subscription eligibility may depend on the account, release, region, and service configuration. Do not rely on an AI response for urgent or emergency decisions.'] },
  { title:'9. Subscriptions and billing', paragraphs:['Paid features, when offered, are purchased and managed through Google Play or another clearly identified authorized store channel. Store pricing, taxes, renewal terms, cancellation, refunds, and payment methods are governed by the applicable store terms and the information shown before purchase.', 'Removing the app does not necessarily cancel a subscription. Use the store subscription-management controls to review or cancel an active subscription. Janani will not treat a purchase as active unless the service can verify the corresponding entitlement.'] },
  { title:'10. No warranty', paragraphs:['To the maximum extent permitted by applicable law, Janani is provided without warranties of uninterrupted operation, medical accuracy, data preservation, or fitness for emergency or clinical use. Nothing in these terms excludes rights that cannot lawfully be excluded.'] },
  { title:'11. Changes', paragraphs:['These terms may be updated as the service changes. The effective date will be revised when updated terms are published.'] },
  { title:'12. Support', paragraphs:['Use Janani’s published support channel for non-sensitive support requests. Do not post personal, account, pregnancy, health, journal, medication, payment, or security-sensitive information in a public issue or public support message.'] },
];

export default function TermsOfServiceScreen() {
  return <LegalDocumentScreen eyebrow="LEGAL" title="Terms of Service" effectiveDate="September 2, 2026" notice="Janani is not a medical device. It does not diagnose, prescribe, monitor a medical condition, or replace a doctor, hospital, emergency service, or individualized medical advice." sections={sections} footer="This in-app copy is intended to match the published Janani Terms of Use for production. The published legal-site copy must be updated to the same effective date before release." />;
}
